//===- Trace.h - XRay Trace Abstraction -----------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Defines the XRay Trace class representing records in an XRay trace file.
//
//===----------------------------------------------------------------------===//
#ifndef LLVM_XRAY_TRACE_H
#define LLVM_XRAY_TRACE_H

#include <cstdint>
#include <vector>

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Error.h"
#include "llvm/XRay/XRayRecord.h"

namespace llvm::xray {

/// Loaded XRay records from an instrumented binary's log file.
///
/// A Trace object represents the records that have been loaded from XRay
/// log files generated by instrumented binaries. We encapsulate the logic of
/// reading the traces in factory functions that populate the Trace object
/// appropriately.
///
/// Trace objects provide an accessor to an XRayFileHeader which says more about
/// details of the file from which the XRay trace was loaded from.
///
/// Usage:
///
///   if (auto TraceOrErr = loadTraceFile("xray-log.something.xray")) {
///     auto& T = *TraceOrErr;
///     // T.getFileHeader() will provide information from the trace header.
///     for (const XRayRecord &R : T) {
///       // ... do something with R here.
///     }
///   } else {
///     // Handle the error here.
///   }
///
class Trace {
  XRayFileHeader FileHeader;
  using RecordVector = std::vector<XRayRecord>;
  RecordVector Records;

  typedef std::vector<XRayRecord>::const_iterator citerator;

  LLVM_ABI friend Expected<Trace> loadTrace(const DataExtractor &, bool);

public:
  /// Unsigned type used to express the number of records.
  using size_type = RecordVector::size_type;
  /// Element type stored in the trace.
  using value_type = RecordVector::value_type;
  /// Const iterator over the loaded XRay records.
  using const_iterator = RecordVector::const_iterator;

  /// Provides access to the loaded XRay trace file header.
  ///
  /// \return Const reference to the loaded XRayFileHeader.
  const XRayFileHeader &getFileHeader() const { return FileHeader; }

  /// Return an iterator to the first record.
  ///
  /// \return Const iterator to the first XRay record.
  const_iterator begin() const { return Records.begin(); }
  /// Return an iterator past the last record.
  ///
  /// \return Const iterator past the last XRay record.
  const_iterator end() const { return Records.end(); }
  /// Return true if the trace contains no records.
  ///
  /// \return True if the trace has no records, false otherwise.
  bool empty() const { return Records.empty(); }
  /// Return the number of records in the trace.
  ///
  /// \return The number of XRay records in the trace.
  size_type size() const { return Records.size(); }
};

/// This function will attempt to load XRay trace records from the provided
/// |Filename|.
///
/// \param Filename Path to the XRay log file to load.
/// \param Sort When true, sort loaded records by TSC ascending.
/// \return The loaded Trace, or an error on failure.
LLVM_ABI Expected<Trace> loadTraceFile(StringRef Filename, bool Sort = false);

/// This function will attempt to load XRay trace records from the provided
/// DataExtractor.
///
/// \param Extractor Data source containing the XRay log bytes.
/// \param Sort When true, sort loaded records by TSC ascending.
/// \return The loaded Trace, or an error on failure.
LLVM_ABI Expected<Trace> loadTrace(const DataExtractor &Extractor,
                                   bool Sort = false);

} // namespace llvm::xray

#endif // LLVM_XRAY_TRACE_H
