//===- Transforms/Instrumentation/InstrProfiling.h --------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
/// \file
/// This file provides the interface for LLVM's PGO Instrumentation lowering
/// pass.
//===----------------------------------------------------------------------===//

#ifndef LLVM_TRANSFORMS_INSTRUMENTATION_INSTRPROFILING_H
#define LLVM_TRANSFORMS_INSTRUMENTATION_INSTRPROFILING_H

#include "llvm/IR/PassManager.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Transforms/Utils/Instrumentation.h"

namespace llvm {

class TargetLibraryInfo;
/// Instrumentation based profiling lowering pass. This pass lowers
/// the profile instrumented code generated by FE or the IR based
/// instrumentation pass.
class InstrProfilingLoweringPass
    : public OptionalPassInfoMixin<InstrProfilingLoweringPass> {
  const InstrProfOptions Options = {};
  // Is this lowering for the context-sensitive instrumentation.
  const bool IsCS = false;

public:
  /// Construct an instrumentation profiling lowering pass with default options.
  InstrProfilingLoweringPass() = default;
  /// Construct an instrumentation profiling lowering pass.
  /// @param Options Options controlling profile data emission and naming.
  /// @param IsCS Whether this lowering is for context-sensitive instrumentation.
  InstrProfilingLoweringPass(const InstrProfOptions &Options, bool IsCS = false)
      : Options(Options), IsCS(IsCS) {}

  /// Lower profile instrumentation intrinsics in \p M.
  /// @param M Module containing instrumented code to lower.
  /// @param AM Module analysis manager providing analyses for the pass.
  /// @return The set of analyses preserved after running this pass.
  LLVM_ABI PreservedAnalyses run(Module &M, ModuleAnalysisManager &AM);
};
} // end namespace llvm

#endif // LLVM_TRANSFORMS_INSTRUMENTATION_INSTRPROFILING_H
