//===- Region.h -------------------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_SANDBOXIR_REGION_H
#define LLVM_SANDBOXIR_REGION_H

#include "llvm/Support/Compiler.h"
#include <memory>

#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/SandboxIR/BasicBlock.h"
#include "llvm/SandboxIR/Function.h"
#include "llvm/SandboxIR/Instruction.h"
#include "llvm/Support/raw_ostream.h"

namespace llvm::sandboxir {

/// Identifiers for Region subclasses used by classof-style checks.
enum RegionClassID {
  /// A Region without score tracking.
  RegionID,
  /// A Region that tracks instruction cost scores.
  RegionWithScoreID,
};

//  Traditional approach: transformations applied vertically for the whole
//  function
//    F
//  +----+
//  |    |
//  |    |
//  |    | -> Transform1 ->  ... -> TransformN -> Check Cost
//  |    |
//  |    |
//  +----+
//
//  Region-based approach: transformations applied horizontally, for each Region
//    F
//  +----+
//  |Rgn1| -> Transform1 ->  ... -> TransformN -> Check Cost
//  |    |
//  |Rgn2| -> Transform1 ->  ... -> TransformN -> Check Cost
//  |    |
//  |Rgn3| -> Transform1 ->  ... -> TransformN -> Check Cost
//  +----+

/// The unit that RegionPasses operate on: new instructions from vectorization.
///
/// The main job of the Region is to point to new instructions generated by
/// vectorization passes. It is the unit that RegionPasses operate on with their
/// runOnRegion() function.
///
/// The region allows us to stack transformations horizontally, meaning that
/// each transformation operates on a single region and the resulting region is
/// the input to the next transformation, as opposed to vertically, which is the
/// common way of applying a transformation across the whole function. This
/// enables us to check for profitability and decide whether we accept or
/// rollback at a region granularity, which is much better than doing this at
/// the function level.
///
/// The region can also hold an ordered sequence of "auxiliary" instructions.
/// This can be used to pass auxiliary information across region passes, like for
/// example the initial seed slice used by the bottom-up vectorizer.
class LLVM_ABI Region {
protected:
  /// All the instructions in the Region. Only new instructions generated during
  /// vectorization are part of the Region.
  SetVector<Instruction *> Insts;
  /// An auxiliary sequence of Instruction-Index pairs.
  SmallVector<Instruction *> Aux;

  /// MDNode that we'll use to mark instructions as being part of the region.
  MDNode *RegionMDN;
  /// Metadata kind used to tag instructions as part of a region.
  static constexpr const char *MDKind = "sandboxvec";
  /// Metadata operand string identifying a sandbox region MDNode.
  static constexpr const char *RegionStr = "sandboxregion";
  /// Metadata kind used to tag auxiliary instructions.
  static constexpr const char *AuxMDKind = "sandboxaux";

  /// The SandboxIR context that owns this region.
  Context &Ctx;

  /// Subclass identifier for this region.
  RegionClassID ID;

  /// ID (for later deregistration) of the "create instruction" callback.
  Context::CallbackID CreateInstCB;
  /// ID (for later deregistration) of the "erase instruction" callback.
  Context::CallbackID EraseInstCB;

  /// Adds \p I to the set without subclass side effects.
  ///
  /// Only to be used when we want to avoid the additional functionality
  /// provided by the subclass, e.g., to avoid score counting when adding
  /// instrs to the aux vector.
  /// NOTE: When an instruction is added to the region we track it cost in the
  /// scoreboard, which currently resides in the region class. However, when we
  /// add an instruction to the auxiliary vector it does get tagged as being a
  /// member of the region (for ownership reasons), but its cost does not get
  /// counted because the instruction hasn't been added in the "normal" way.
  /// \param I Instruction to add.
  void addRaw(Instruction *I) {
    Insts.insert(I);
    // TODO: Consider tagging instructions lazily.
    cast<llvm::Instruction>(I->Val)->setMetadata(MDKind, RegionMDN);
  }
  /// Adds I to the set. This is the main API for adding an instruction to the
  /// region.
  /// \param I Instruction to add.
  virtual void add(Instruction *I) { addRaw(I); }
  /// Removes I from the set.
  /// \param I Instruction to remove.
  virtual void remove(Instruction *I);
  friend class Context; // The callbacks need to call add() and remove().
  friend class RegionInternalsAttorney; // For unit tests.

  /// Set \p I as the \p Idx'th element in the auxiliary vector.
  /// NOTE: This is for internal use, it does not set the metadata.
  /// \param Idx Index in the auxiliary vector.
  /// \param I Instruction to place at \p Idx.
  void setAux(unsigned Idx, Instruction *I);
  /// Helper for dropping Aux metadata for \p I.
  /// \param I Instruction whose Aux metadata should be dropped.
  void dropAuxMetadata(Instruction *I);
  /// Remove instruction \p I from Aux and drop metadata.
  /// \param I Instruction to remove from the auxiliary vector.
  void removeFromAux(Instruction *I);

  /// Construct a region of the given subclass in \p Ctx.
  /// \param Ctx SandboxIR context.
  /// \param ID Subclass identifier.
  Region(Context &Ctx, RegionClassID ID);

  /// Create regions of type \p RegionT from region metadata in \p F.
  /// \param F Function whose instructions may carry region metadata.
  /// \param Factory Callable that creates a new RegionT.
  /// \Returns the regions reconstructed from metadata.
  template <typename RegionT, typename RegionFactoryT>
  static SmallVector<std::unique_ptr<RegionT>>
  createRegionsFromMD(Function &F, RegionFactoryT Factory) {
    SmallVector<std::unique_ptr<RegionT>> Regions;
    DenseMap<MDNode *, RegionT *> MDNToRegion;
    for (BasicBlock &BB : F) {
      for (Instruction &Inst : BB) {
        auto *LLVMI = cast<llvm::Instruction>(Inst.Val);
        RegionT *R = nullptr;
        if (auto *MDN = LLVMI->getMetadata(MDKind)) {
          auto [It, Inserted] = MDNToRegion.try_emplace(MDN);
          if (Inserted) {
            Regions.push_back(Factory());
            R = Regions.back().get();
            It->second = R;
          } else {
            R = It->second;
          }
          R->addRaw(&Inst);
        }
        if (auto *AuxMDN = LLVMI->getMetadata(AuxMDKind)) {
          llvm::Constant *IdxC =
              dyn_cast<ConstantAsMetadata>(AuxMDN->getOperand(0))->getValue();
          auto Idx = cast<llvm::ConstantInt>(IdxC)->getSExtValue();
          if (R == nullptr) {
            errs() << "No region specified for Aux: '" << *LLVMI << "'\n";
            reportFatalUsageError("No region specified for Aux!");
          }
          R->setAux(Idx, &Inst);
        }
      }
    }
#ifndef NDEBUG
    // Check that there are no gaps in the Aux vector.
    for (auto &RPtr : Regions)
      for (auto *I : RPtr->getAux())
        assert(I != nullptr && "Gap in Aux!");
#endif
    return Regions;
  }

public:
  /// Construct a plain Region in \p Ctx.
  /// \param Ctx SandboxIR context.
  Region(Context &Ctx) : Region(Ctx, RegionClassID::RegionID) {}
  /// Destroy the region and unregister its callbacks.
  virtual ~Region();
  // Disable copies to avoid unregistering the callback more than once.
  /// Copy construction is not supported.
  /// \param Other Unused copy source.
  Region(const Region &Other) = delete;
  // Moves are allowed.
  /// Move-construct a region.
  /// \param Other Region to move from.
  Region(Region &&Other) = default;

  /// Returns the SandboxIR context for this region.
  /// \Returns The SandboxIR context.
  Context &getContext() const { return Ctx; }
  /// Returns true if I is in the Region.
  /// \param I Instruction to test for membership.
  /// \Returns True if \p I is in the Region.
  bool contains(Instruction *I) const { return Insts.contains(I); }
  /// Returns true if the Region has no instructions.
  /// \Returns True if the Region has no instructions.
  bool empty() const { return Insts.empty(); }
  /// Set the auxiliary vector.
  /// \param Aux Instructions to use as the auxiliary sequence.
  void setAux(ArrayRef<Instruction *> Aux);
  /// The auxiliary instruction sequence for this region.
  /// \Returns the auxiliary vector.
  const SmallVector<Instruction *> &getAux() const { return Aux; }
  /// Clears all auxiliary data.
  void clearAux();

  /// Iterator over the instructions in this region.
  using iterator = decltype(Insts.begin());
  /// Returns an iterator to the first instruction in the region.
  /// \Returns An iterator to the first instruction.
  iterator begin() { return Insts.begin(); }
  /// Returns an iterator past the last instruction in the region.
  /// \Returns An iterator past the last instruction.
  iterator end() { return Insts.end(); }
  /// Returns a range over the instructions in this region.
  /// \Returns A range over the region's instructions.
  iterator_range<iterator> insts() { return make_range(begin(), end()); }

  /// Create regions from region metadata attached to instructions in \p F.
  /// \param F Function whose instructions may carry region metadata.
  /// \Returns the regions reconstructed from metadata.
  static SmallVector<std::unique_ptr<Region>> createRegionsFromMD(Function &F);

  /// Returns the subclass identifier for this region.
  /// \Returns The subclass identifier.
  RegionClassID getSubclassID() const { return ID; }

#ifndef NDEBUG
  /// This is an expensive check, meant for testing.
  /// \param Other Region to compare against.
  /// \Returns True if this region equals \p Other.
  LLVM_ABI bool operator==(const Region &Other) const;
  /// Returns true if this region is not equal to \p Other.
  /// \param Other Region to compare against.
  /// \Returns True if this region is not equal to \p Other.
  bool operator!=(const Region &Other) const { return !(*this == Other); }

  /// Print this region to \p OS.
  /// \param OS Output stream.
  LLVM_ABI void dump(raw_ostream &OS) const;
  /// Dump this region to the debug stream.
  void dump() const;
  /// Print \p Rgn to \p OS.
  /// \param OS Output stream.
  /// \param Rgn Region to print.
  /// \Returns The output stream \p OS.
  friend raw_ostream &operator<<(raw_ostream &OS, const Region &Rgn) {
    Rgn.dump(OS);
    return OS;
  }
#endif
};

/// A helper client-attorney class for unit tests.
class RegionInternalsAttorney {
public:
  /// Add \p I to \p Rgn via the protected Region::add API.
  /// \param Rgn Region to modify.
  /// \param I Instruction to add.
  static void add(Region &Rgn, Instruction *I) { Rgn.add(I); }
  /// Remove \p I from \p Rgn via the protected Region::remove API.
  /// \param Rgn Region to modify.
  /// \param I Instruction to remove.
  static void remove(Region &Rgn, Instruction *I) { Rgn.remove(I); }
};

} // namespace llvm::sandboxir

#endif // LLVM_SANDBOXIR_REGION_H
