//===-- FaultMapParser.h - Parser for the  "FaultMaps" section --*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_OBJECT_FAULTMAPPARSER_H
#define LLVM_OBJECT_FAULTMAPPARSER_H

#include "llvm/Support/Compiler.h"
#include "llvm/Support/Endian.h"
#include <cassert>
#include <cstdint>

namespace llvm {

class raw_ostream;

/// A parser for the __llvm_faultmaps section.
///
/// Generated by the FaultMaps class declared in llvm/CodeGen/FaultMaps.h.
/// This parser is version locked with with the __llvm_faultmaps section
/// generated by the version of LLVM that includes it.  No guarantees are made
/// with respect to forward or backward compatibility.
class FaultMapParser {
  using FaultMapVersionType = uint8_t;
  using Reserved0Type = uint8_t;
  using Reserved1Type = uint16_t;
  using NumFunctionsType = uint32_t;

  static const size_t FaultMapVersionOffset = 0;
  static const size_t Reserved0Offset =
      FaultMapVersionOffset + sizeof(FaultMapVersionType);
  static const size_t Reserved1Offset = Reserved0Offset + sizeof(Reserved0Type);
  static const size_t NumFunctionsOffset =
      Reserved1Offset + sizeof(Reserved1Type);
  static const size_t FunctionInfosOffset =
      NumFunctionsOffset + sizeof(NumFunctionsType);

  const uint8_t *P;
  const uint8_t *E;

  template <typename T> static T read(const uint8_t *P, const uint8_t *E) {
    assert(P + sizeof(T) <= E && "out of bounds read!");
    return support::endian::read<T, llvm::endianness::little>(P);
  }

public:
  /// Kinds of potentially-faulting operations recorded in a fault map.
  enum FaultKind {
    FaultingLoad = 1, ///< A load that may fault.
    FaultingLoadStore, ///< A load-store that may fault.
    FaultingStore, ///< A store that may fault.
    FaultKindMax ///< Sentinel one past the last valid fault kind.
  };

  /// Accessor for a single function fault-info record.
  class FunctionFaultInfoAccessor {
    using FaultKindType = uint32_t;
    using FaultingPCOffsetType = uint32_t;
    using HandlerPCOffsetType = uint32_t;

    static const size_t FaultKindOffset = 0;
    static const size_t FaultingPCOffsetOffset =
        FaultKindOffset + sizeof(FaultKindType);
    static const size_t HandlerPCOffsetOffset =
        FaultingPCOffsetOffset + sizeof(FaultingPCOffsetType);

    const uint8_t *P;
    const uint8_t *E;

  public:
    /// Size in bytes of one function fault-info record.
    static const size_t Size =
        HandlerPCOffsetOffset + sizeof(HandlerPCOffsetType);

    /// Construct an accessor for the fault-info record at \p P.
    ///
    /// \param P Pointer to the start of the fault-info record.
    /// \param E One-past-the-end pointer for the fault map buffer.
    explicit FunctionFaultInfoAccessor(const uint8_t *P, const uint8_t *E)
        : P(P), E(E) {}

    /// Get the kind of faulting operation for this record.
    ///
    /// \return The fault kind for this record.
    FaultKindType getFaultKind() const {
      return read<FaultKindType>(P + FaultKindOffset, E);
    }

    /// Get the PC offset of the faulting instruction.
    ///
    /// \return The PC offset of the faulting instruction.
    FaultingPCOffsetType getFaultingPCOffset() const {
      return read<FaultingPCOffsetType>(P + FaultingPCOffsetOffset, E);
    }

    /// Get the PC offset of the fault handler.
    ///
    /// \return The PC offset of the fault handler.
    HandlerPCOffsetType getHandlerPCOffset() const {
      return read<HandlerPCOffsetType>(P + HandlerPCOffsetOffset, E);
    }
  };

  /// Accessor for a function info record and its nested fault infos.
  class FunctionInfoAccessor {
    using FunctionAddrType = uint64_t;
    using NumFaultingPCsType = uint32_t;
    using ReservedType = uint32_t;

    static const size_t FunctionAddrOffset = 0;
    static const size_t NumFaultingPCsOffset =
        FunctionAddrOffset + sizeof(FunctionAddrType);
    static const size_t ReservedOffset =
        NumFaultingPCsOffset + sizeof(NumFaultingPCsType);
    static const size_t FunctionFaultInfosOffset =
        ReservedOffset + sizeof(ReservedType);
    static const size_t FunctionInfoHeaderSize = FunctionFaultInfosOffset;

    const uint8_t *P = nullptr;
    const uint8_t *E = nullptr;

  public:
    /// Construct an empty function info accessor.
    FunctionInfoAccessor() = default;

    /// Construct an accessor for the function info record at \p P.
    ///
    /// \param P Pointer to the start of the function info record.
    /// \param E One-past-the-end pointer for the fault map buffer.
    explicit FunctionInfoAccessor(const uint8_t *P, const uint8_t *E)
        : P(P), E(E) {}

    /// Get the address of the function described by this record.
    ///
    /// \return The address of the function.
    FunctionAddrType getFunctionAddr() const {
      return read<FunctionAddrType>(P + FunctionAddrOffset, E);
    }

    /// Get the number of faulting PCs recorded for this function.
    ///
    /// \return The number of faulting PCs for this function.
    NumFaultingPCsType getNumFaultingPCs() const {
      return read<NumFaultingPCsType>(P + NumFaultingPCsOffset, E);
    }

    /// Get the fault-info accessor for the entry at \p Index.
    ///
    /// \param Index Zero-based index of the fault-info entry.
    /// \return An accessor for the fault-info entry at \p Index.
    FunctionFaultInfoAccessor getFunctionFaultInfoAt(uint32_t Index) const {
      assert(Index < getNumFaultingPCs() && "index out of bounds!");
      const uint8_t *Begin = P + FunctionFaultInfosOffset +
                             FunctionFaultInfoAccessor::Size * Index;
      return FunctionFaultInfoAccessor(Begin, E);
    }

    /// Get an accessor for the next function info record in the section.
    ///
    /// \return An accessor for the next function info record.
    FunctionInfoAccessor getNextFunctionInfo() const {
      size_t MySize = FunctionInfoHeaderSize +
                      getNumFaultingPCs() * FunctionFaultInfoAccessor::Size;

      const uint8_t *Begin = P + MySize;
      assert(Begin < E && "out of bounds!");
      return FunctionInfoAccessor(Begin, E);
    }
  };

  /// Construct a parser over the fault map bytes in [\p Begin, \p End).
  ///
  /// \param Begin Pointer to the start of the __llvm_faultmaps section.
  /// \param End One-past-the-end pointer for the section bytes.
  explicit FaultMapParser(const uint8_t *Begin, const uint8_t *End)
      : P(Begin), E(End) {}

  /// Get the fault map format version.
  ///
  /// \return The fault map format version.
  FaultMapVersionType getFaultMapVersion() const {
    auto Version = read<FaultMapVersionType>(P + FaultMapVersionOffset, E);
    assert(Version == 1 && "only version 1 supported!");
    return Version;
  }

  /// Get the number of function info records in the fault map.
  ///
  /// \return The number of function info records.
  NumFunctionsType getNumFunctions() const {
    return read<NumFunctionsType>(P + NumFunctionsOffset, E);
  }

  /// Get an accessor for the first function info record.
  ///
  /// \return An accessor for the first function info record.
  FunctionInfoAccessor getFirstFunctionInfo() const {
    const uint8_t *Begin = P + FunctionInfosOffset;
    return FunctionInfoAccessor(Begin, E);
  }
};

/// Print \p FFI to \p OS as a human-readable function fault-info record.
///
/// \param OS Stream to write to.
/// \param FFI Function fault-info accessor to print.
/// \return A reference to \p OS.
LLVM_ABI raw_ostream &
operator<<(raw_ostream &OS,
           const FaultMapParser::FunctionFaultInfoAccessor &FFI);

/// Print \p FI to \p OS as a human-readable function info record.
///
/// \param OS Stream to write to.
/// \param FI Function info accessor to print.
/// \return A reference to \p OS.
LLVM_ABI raw_ostream &operator<<(raw_ostream &OS,
                                 const FaultMapParser::FunctionInfoAccessor &FI);

/// Print \p FMP to \p OS as a human-readable fault map.
///
/// \param OS Stream to write to.
/// \param FMP Fault map parser to print.
/// \return A reference to \p OS.
LLVM_ABI raw_ostream &operator<<(raw_ostream &OS, const FaultMapParser &FMP);

} // namespace llvm

#endif
