//===- PDBSymbolFunc.h - class representing a function instance -*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_DEBUGINFO_PDB_PDBSYMBOLFUNC_H
#define LLVM_DEBUGINFO_PDB_PDBSYMBOLFUNC_H

#include "llvm/DebugInfo/PDB/IPDBRawSymbol.h"
#include "llvm/DebugInfo/PDB/PDBSymbolTypeFunctionSig.h"
#include "llvm/Support/Compiler.h"

#include "PDBSymbol.h"
#include "PDBTypes.h"

namespace llvm {

namespace pdb {

class PDBSymDumper;
class PDBSymbolData;
template <typename ChildType> class IPDBEnumChildren;

/// PDB symbol for a function or method definition.
class LLVM_ABI PDBSymbolFunc : public PDBSymbol {
private:
  using PDBSymbol::PDBSymbol;
  friend class PDBSymbol;

public:
  /// Symbol tag for function symbols.
  static const PDB_SymType Tag = PDB_SymType::Function;

  /// Return true if \p S is a function symbol.
  ///
  /// \param S Symbol to test.
  ///
  /// \returns True if \p S is a function symbol.
  static bool classof(const PDBSymbol *S) { return S->getSymTag() == Tag; }

  /// Dump this function symbol using the given dumper.
  ///
  /// \param Dumper Visitor used to format and emit the symbol.
  void dump(PDBSymDumper &Dumper) const override;

  /// Return true if this function is a destructor.
  ///
  /// \returns True if this function is a destructor.
  bool isDestructor() const;

  /// Enumerate this function's parameter data symbols.
  ///
  /// \returns An enumerator over parameter symbols.
  std::unique_ptr<IPDBEnumChildren<PDBSymbolData>> getArguments() const;

  /// Return the access level of this member function.
  ///
  /// \returns The access level of this member function.
  FORWARD_SYMBOL_METHOD(getAccess)
  /// Return the section-relative address offset of this function.
  ///
  /// \returns The section-relative address offset of this function.
  FORWARD_SYMBOL_METHOD(getAddressOffset)
  /// Return the section index of this function's address.
  ///
  /// \returns The section index of this function's address.
  FORWARD_SYMBOL_METHOD(getAddressSection)
  /// Return the symbol id of this function's class parent.
  ///
  /// \returns The symbol id of this function's class parent.
  decltype(auto) getClassParentId() const {
    return RawSymbol->getClassParentId();
  }
  /// Return the class parent of this member function.
  ///
  /// \returns The class parent symbol, or nullptr if none.
  std::unique_ptr<PDBSymbol> getClassParent() const {
    uint32_t Id = getClassParentId();
    return getConcreteSymbolByIdHelper<PDBSymbol>(Id);
  }
  /// Return true if this function was generated by the compiler.
  ///
  /// \returns True if this function was generated by the compiler.
  FORWARD_SYMBOL_METHOD(isCompilerGenerated)
  /// Return true if this constructor initializes a virtual base.
  ///
  /// \returns True if this constructor initializes a virtual base.
  FORWARD_SYMBOL_METHOD(isConstructorVirtualBase)
  /// Return true if this function type is const-qualified.
  ///
  /// \returns True if this function type is const-qualified.
  FORWARD_SYMBOL_METHOD(isConstType)
  /// Return true if this function returns a C++ UDT.
  ///
  /// \returns True if this function returns a C++ UDT.
  FORWARD_SYMBOL_METHOD(isCxxReturnUdt)
  /// Return true if this function uses a custom calling convention.
  ///
  /// \returns True if this function uses a custom calling convention.
  FORWARD_SYMBOL_METHOD(hasCustomCallingConvention)
  /// Return true if this function uses a far return.
  ///
  /// \returns True if this function uses a far return.
  FORWARD_SYMBOL_METHOD(hasFarReturn)
  /// Return true if this function uses alloca.
  ///
  /// \returns True if this function uses alloca.
  FORWARD_SYMBOL_METHOD(hasAlloca)
  /// Return true if this function uses C++ exception handling.
  ///
  /// \returns True if this function uses C++ exception handling.
  FORWARD_SYMBOL_METHOD(hasEH)
  /// Return true if this function uses asynchronous exception handling.
  ///
  /// \returns True if this function uses asynchronous exception handling.
  FORWARD_SYMBOL_METHOD(hasEHa)
  /// Return true if this function contains inline assembly.
  ///
  /// \returns True if this function contains inline assembly.
  FORWARD_SYMBOL_METHOD(hasInlAsm)
  /// Return true if this function uses longjmp.
  ///
  /// \returns True if this function uses longjmp.
  FORWARD_SYMBOL_METHOD(hasLongJump)
  /// Return true if this function uses structured exception handling.
  ///
  /// \returns True if this function uses structured exception handling.
  FORWARD_SYMBOL_METHOD(hasSEH)
  /// Return true if this function has security checks.
  ///
  /// \returns True if this function has security checks.
  FORWARD_SYMBOL_METHOD(hasSecurityChecks)
  /// Return true if this function uses setjmp.
  ///
  /// \returns True if this function uses setjmp.
  FORWARD_SYMBOL_METHOD(hasSetJump)
  /// Return true if this function uses an interrupt return.
  ///
  /// \returns True if this function uses an interrupt return.
  FORWARD_SYMBOL_METHOD(hasInterruptReturn)
  /// Return true if this is an introducing virtual function.
  ///
  /// \returns True if this is an introducing virtual function.
  FORWARD_SYMBOL_METHOD(isIntroVirtualFunction)
  /// Return true if this function has the inline attribute.
  ///
  /// \returns True if this function has the inline attribute.
  FORWARD_SYMBOL_METHOD(hasInlineAttribute)
  /// Return true if this function is declared naked.
  ///
  /// \returns True if this function is declared naked.
  FORWARD_SYMBOL_METHOD(isNaked)
  /// Return true if this function is static.
  ///
  /// \returns True if this function is static.
  FORWARD_SYMBOL_METHOD(isStatic)
  /// Return the length in bytes of this function.
  ///
  /// \returns The length in bytes of this function.
  FORWARD_SYMBOL_METHOD(getLength)
  /// Return the symbol id of this function's lexical parent.
  ///
  /// \returns The symbol id of this function's lexical parent.
  decltype(auto) getLexicalParentId() const {
    return RawSymbol->getLexicalParentId();
  }
  /// Return the lexical parent of this function.
  ///
  /// \returns The lexical parent symbol, or nullptr if none.
  std::unique_ptr<PDBSymbol> getLexicalParent() const {
    uint32_t Id = getLexicalParentId();
    return getConcreteSymbolByIdHelper<PDBSymbol>(Id);
  }
  /// Return the register id used as the local base pointer.
  ///
  /// \returns The register id used as the local base pointer.
  FORWARD_SYMBOL_METHOD(getLocalBasePointerRegisterId)
  /// Return the location type of this function.
  ///
  /// \returns The location type of this function.
  FORWARD_SYMBOL_METHOD(getLocationType)
  /// Return the name of this function.
  ///
  /// \returns The name of this function.
  FORWARD_SYMBOL_METHOD(getName)
  /// Return true if this function has a frame pointer.
  ///
  /// \returns True if this function has a frame pointer.
  FORWARD_SYMBOL_METHOD(hasFramePointer)
  /// Return true if this function has the noinline attribute.
  ///
  /// \returns True if this function has the noinline attribute.
  FORWARD_SYMBOL_METHOD(hasNoInlineAttribute)
  /// Return true if this function has the noreturn attribute.
  ///
  /// \returns True if this function has the noreturn attribute.
  FORWARD_SYMBOL_METHOD(hasNoReturnAttribute)
  /// Return true if this function's code is unreachable.
  ///
  /// \returns True if this function's code is unreachable.
  FORWARD_SYMBOL_METHOD(isUnreached)
  /// Return true if this function has no stack ordering.
  ///
  /// \returns True if this function has no stack ordering.
  FORWARD_SYMBOL_METHOD(getNoStackOrdering)
  /// Return true if this function has optimized-code debug info.
  ///
  /// \returns True if this function has optimized-code debug info.
  FORWARD_SYMBOL_METHOD(hasOptimizedCodeDebugInfo)
  /// Return true if this function is pure virtual.
  ///
  /// \returns True if this function is pure virtual.
  FORWARD_SYMBOL_METHOD(isPureVirtual)
  /// Return the relative virtual address of this function.
  ///
  /// \returns The relative virtual address of this function.
  FORWARD_SYMBOL_METHOD(getRelativeVirtualAddress)
  /// Return the metadata token associated with this managed function.
  ///
  /// \returns The metadata token associated with this managed function.
  FORWARD_SYMBOL_METHOD(getToken)
  /// Return the symbol id of this function's signature type.
  ///
  /// \returns The symbol id of this function's signature type.
  decltype(auto) getSignatureId() const { return RawSymbol->getTypeId(); }
  /// Return this function's signature type.
  ///
  /// \returns The function signature symbol, or nullptr if none.
  std::unique_ptr<PDBSymbolTypeFunctionSig> getSignature() const {
    uint32_t Id = getSignatureId();
    return getConcreteSymbolByIdHelper<PDBSymbolTypeFunctionSig>(Id);
  }
  /// Return true if this function type is unaligned.
  ///
  /// \returns True if this function type is unaligned.
  FORWARD_SYMBOL_METHOD(isUnalignedType)
  /// Return the undecorated (demangled) name of this function.
  ///
  /// \returns The undecorated (demangled) name of this function.
  FORWARD_SYMBOL_METHOD(getUndecoratedName)
  /// Return true if this function is virtual.
  ///
  /// \returns True if this function is virtual.
  FORWARD_SYMBOL_METHOD(isVirtual)
  /// Return the virtual address of this function.
  ///
  /// \returns The virtual address of this function.
  FORWARD_SYMBOL_METHOD(getVirtualAddress)
  /// Return the virtual function table offset for this function.
  ///
  /// \returns The virtual function table offset for this function.
  FORWARD_SYMBOL_METHOD(getVirtualBaseOffset)
  /// Return true if this function type is volatile-qualified.
  ///
  /// \returns True if this function type is volatile-qualified.
  FORWARD_SYMBOL_METHOD(isVolatileType)

  /// Enumerate source line numbers covered by this function.
  ///
  /// \returns An enumerator over line-number entries for this function.
  std::unique_ptr<IPDBEnumLineNumbers> getLineNumbers() const;

  /// Return the compiland id associated with this function's line numbers.
  ///
  /// \returns The first line's compiland id, or 0 if none are available.
  uint32_t getCompilandId() const;
};

} // namespace pdb
} // namespace llvm

#endif // LLVM_DEBUGINFO_PDB_PDBSYMBOLFUNC_H
