//===- PDBSymbolData.h - PDB data (e.g. variable) accessors -----*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_DEBUGINFO_PDB_PDBSYMBOLDATA_H
#define LLVM_DEBUGINFO_PDB_PDBSYMBOLDATA_H

#include "PDBSymbol.h"
#include "PDBTypes.h"
#include "llvm/DebugInfo/PDB/IPDBRawSymbol.h"
#include "llvm/Support/Compiler.h"

namespace llvm {

namespace pdb {

class PDBSymDumper;

/// PDB symbol for a data item such as a variable or data member.
///
/// Exposes location, type, and value accessors for a SymTagData symbol in the
/// PDB lexical hierarchy.
class LLVM_ABI PDBSymbolData : public PDBSymbol {
private:
  using PDBSymbol::PDBSymbol;
  friend class PDBSymbol;

public:
  /// Symbol tag for data symbols.
  static const PDB_SymType Tag = PDB_SymType::Data;

  /// Return true if \p S is a data symbol.
  ///
  /// \param S Symbol to test.
  ///
  /// \returns True if \p S is a data symbol.
  static bool classof(const PDBSymbol *S) { return S->getSymTag() == Tag; }

  /// Dump this data symbol using the given dumper.
  ///
  /// \param Dumper Visitor used to format and emit the symbol.
  void dump(PDBSymDumper &Dumper) const override;

  /// Return the access level of this data member.
  ///
  /// \returns The access level of this data member.
  FORWARD_SYMBOL_METHOD(getAccess)
  /// Return the section-relative address offset of this data symbol.
  ///
  /// \returns The section-relative address offset.
  FORWARD_SYMBOL_METHOD(getAddressOffset)
  /// Return the section index of this data symbol's address.
  ///
  /// \returns The section index of this data symbol's address.
  FORWARD_SYMBOL_METHOD(getAddressSection)
  /// Return true if the address of this data symbol has been taken.
  ///
  /// \returns True if the address of this data symbol has been taken.
  FORWARD_SYMBOL_METHOD(getAddressTaken)
  /// Return the bit position of this bitfield member.
  ///
  /// \returns The bit position of this bitfield member.
  FORWARD_SYMBOL_METHOD(getBitPosition)
  /// Return the symbol id of this data symbol's class parent.
  ///
  /// \returns The symbol id of this data symbol's class parent.
  decltype(auto) getClassParentId() const {
    return RawSymbol->getClassParentId();
  }
  /// Return the class parent of this data member.
  ///
  /// \returns The class parent symbol, or nullptr if none.
  std::unique_ptr<PDBSymbol> getClassParent() const {
    uint32_t Id = getClassParentId();
    return getConcreteSymbolByIdHelper<PDBSymbol>(Id);
  }
  /// Return true if this data symbol was generated by the compiler.
  ///
  /// \returns True if this data symbol was generated by the compiler.
  FORWARD_SYMBOL_METHOD(isCompilerGenerated)
  /// Return true if this data type is const-qualified.
  ///
  /// \returns True if this data type is const-qualified.
  FORWARD_SYMBOL_METHOD(isConstType)
  /// Return the data kind of this data symbol.
  ///
  /// \returns The data kind of this data symbol.
  FORWARD_SYMBOL_METHOD(getDataKind)
  /// Return true if this data symbol is aggregated.
  ///
  /// \returns True if this data symbol is aggregated.
  FORWARD_SYMBOL_METHOD(isAggregated)
  /// Return true if this data symbol is split (PGO cold/hot).
  ///
  /// \returns True if this data symbol is split (PGO cold/hot).
  FORWARD_SYMBOL_METHOD(isSplitted)
  /// Return the length in bytes of this data symbol.
  ///
  /// \returns The length in bytes of this data symbol.
  FORWARD_SYMBOL_METHOD(getLength)
  /// Return the symbol id of this data symbol's lexical parent.
  ///
  /// \returns The symbol id of this data symbol's lexical parent.
  decltype(auto) getLexicalParentId() const {
    return RawSymbol->getLexicalParentId();
  }
  /// Return the lexical parent of this data symbol.
  ///
  /// \returns The lexical parent symbol, or nullptr if none.
  std::unique_ptr<PDBSymbol> getLexicalParent() const {
    uint32_t Id = getLexicalParentId();
    return getConcreteSymbolByIdHelper<PDBSymbol>(Id);
  }
  /// Return the location type of this data symbol.
  ///
  /// \returns The location type of this data symbol.
  FORWARD_SYMBOL_METHOD(getLocationType)
  /// Return the name of this data symbol.
  ///
  /// \returns The name of this data symbol.
  FORWARD_SYMBOL_METHOD(getName)
  /// Return the offset associated with this data symbol.
  ///
  /// \returns The offset associated with this data symbol.
  FORWARD_SYMBOL_METHOD(getOffset)
  /// Return the register id where this data symbol is located.
  ///
  /// \returns The register id where this data symbol is located.
  FORWARD_SYMBOL_METHOD(getRegisterId)
  /// Return the relative virtual address of this data symbol.
  ///
  /// \returns The relative virtual address of this data symbol.
  FORWARD_SYMBOL_METHOD(getRelativeVirtualAddress)
  /// Return the slot index associated with this data symbol.
  ///
  /// \returns The slot index associated with this data symbol.
  FORWARD_SYMBOL_METHOD(getSlot)
  /// Return the metadata token associated with this managed data symbol.
  ///
  /// \returns The metadata token for this managed data symbol.
  FORWARD_SYMBOL_METHOD(getToken)
  /// Return the symbol id of this data symbol's type.
  ///
  /// \returns The symbol id of this data symbol's type.
  decltype(auto) getTypeId() const { return RawSymbol->getTypeId(); }
  /// Return the type of this data symbol.
  ///
  /// \returns The type symbol, or nullptr if none.
  std::unique_ptr<PDBSymbol> getType() const {
    uint32_t Id = getTypeId();
    return getConcreteSymbolByIdHelper<PDBSymbol>(Id);
  }
  /// Return true if this data type is unaligned.
  ///
  /// \returns True if this data type is unaligned.
  FORWARD_SYMBOL_METHOD(isUnalignedType)
  /// Return the constant value associated with this data symbol.
  ///
  /// \returns The constant value associated with this data symbol.
  FORWARD_SYMBOL_METHOD(getValue)
  /// Return the virtual address of this data symbol.
  ///
  /// \returns The virtual address of this data symbol.
  FORWARD_SYMBOL_METHOD(getVirtualAddress)
  /// Return true if this data type is volatile-qualified.
  ///
  /// \returns True if this data type is volatile-qualified.
  FORWARD_SYMBOL_METHOD(isVolatileType)

  /// Enumerate source line numbers covered by this data symbol.
  ///
  /// \returns An enumerator over line-number entries, or nullptr if none.
  std::unique_ptr<IPDBEnumLineNumbers> getLineNumbers() const;

  /// Return the compiland id associated with this data symbol.
  ///
  /// \returns The first line's or section contrib's compiland id, or 0 if none
  /// are available.
  uint32_t getCompilandId() const;
};
} // namespace pdb
} // namespace llvm

#endif // LLVM_DEBUGINFO_PDB_PDBSYMBOLDATA_H
