//===- BTFParser.h ----------------------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// BTFParser reads .BTF and .BTF.ext ELF sections generated by LLVM
// BPF backend and provides introspection for the stored information.
// Currently the following information is accessible:
// - string table;
// - instruction offset to line information mapping;
// - types table;
// - CO-RE relocations table.
//
// See llvm/DebugInfo/BTF/BTF.h for some details about binary format
// and links to Linux Kernel documentation.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_DEBUGINFO_BTF_BTFPARSER_H
#define LLVM_DEBUGINFO_BTF_BTFPARSER_H

#include "llvm/ADT/DenseMap.h"
#include "llvm/DebugInfo/BTF/BTF.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DataExtractor.h"

namespace llvm {
/// Bring `object::ObjectFile` into this namespace.
using object::ObjectFile;
/// Bring `object::SectionedAddress` into this namespace.
using object::SectionedAddress;
/// Bring `object::SectionRef` into this namespace.
using object::SectionRef;

/// Parser for BPF Type Format (.BTF and .BTF.ext) ELF sections.
///
/// BTFParser reads .BTF and .BTF.ext ELF sections generated by LLVM
/// BPF backend and provides introspection for the stored information.
/// Currently the following information is accessible:
/// - string table;
/// - instruction offset to line information mapping;
/// - types table;
/// - CO-RE relocations table.
///
/// See llvm/DebugInfo/BTF/BTF.h for some details about binary format
/// and links to Linux Kernel documentation.
class BTFParser {
  using BTFLinesVector = SmallVector<BTF::BPFLineInfo, 0>;
  using BTFRelocVector = SmallVector<BTF::BPFFieldReloc, 0>;

  // In BTF strings are stored as a continuous memory region with
  // individual strings separated by 0 bytes. Strings are identified
  // by an offset in such region.
  // The `StringsTable` points to this region in the parsed ObjectFile.
  StringRef StringsTable;

  // A copy of types table from the object file but using native byte
  // order. Should not be too big in practice, e.g. for ~250MiB vmlinux
  // image it is ~4MiB.
  SmallVector<uint8_t, 0> TypesBuffer;

  // Maps ELF section number to instruction line number information.
  // Each BTFLinesVector is sorted by `InsnOffset` to allow fast lookups.
  DenseMap<uint64_t, BTFLinesVector> SectionLines;

  // Maps ELF section number to CO-RE relocation information.
  // Each BTFRelocVector is sorted by `InsnOffset` to allow fast lookups.
  DenseMap<uint64_t, BTFRelocVector> SectionRelocs;

  // Vector of pointers to all known types, index in this vector
  // equals to logical type BTF id.
  // Pointers point to memory owned by `TypesBuffer`
  // (except pointer at index 0, which is statically allocated).
  std::vector<const BTF::CommonType *> Types;

  struct ParseContext;
  Error parseBTF(ParseContext &Ctx, SectionRef BTF);
  Error parseBTFExt(ParseContext &Ctx, SectionRef BTFExt);
  Error parseLineInfo(ParseContext &Ctx, DataExtractor &Extractor,
                      uint64_t LineInfoStart, uint64_t LineInfoEnd);
  Error parseRelocInfo(ParseContext &Ctx, DataExtractor &Extractor,
                       uint64_t RelocInfoStart, uint64_t RelocInfoEnd);
  Error parseTypesInfo(ParseContext &Ctx, uint64_t TypesInfoStart,
                       StringRef RawData);

public:
  /// Look up a string in the .BTF section's string table.
  ///
  /// \p Offset is relative to the string table start.
  ///
  /// \param Offset Byte offset from the start of the string table.
  /// \returns The string at \p Offset.
  LLVM_ABI StringRef findString(uint32_t Offset) const;

  /// Find line information for an exact instruction address.
  ///
  /// Address match is exact (contrary to DWARFContext). If information is
  /// present, the returned pointer refers to an object owned by this class.
  ///
  /// \param Address Section and instruction offset to look up.
  /// \returns A pointer to the line info, or \c nullptr if none was found.
  LLVM_ABI const BTF::BPFLineInfo *findLineInfo(SectionedAddress Address) const;

  /// Find CO-RE relocation information for an instruction address.
  ///
  /// If information is present, the returned pointer refers to an object
  /// owned by this class.
  ///
  /// \param Address Section and instruction offset to look up.
  /// \returns A pointer to the relocation, or \c nullptr if none was found.
  LLVM_ABI const BTF::BPFFieldReloc *
  findFieldReloc(SectionedAddress Address) const;

  /// Write a human-readable form of a CO-RE relocation into \p Result.
  ///
  /// The output is for display purposes only. See the implementation for
  /// details of the format.
  ///
  /// \param Reloc CO-RE field relocation to describe.
  /// \param Result Buffer that receives the formatted text.
  LLVM_ABI void symbolize(const BTF::BPFFieldReloc *Reloc,
                          SmallVectorImpl<char> &Result) const;

  /// Look up the BTF type definition with identifier \p Id.
  ///
  /// If information is present, the returned pointer refers to an object
  /// owned by this class.
  ///
  /// \param Id Logical BTF type identifier (index in the types table).
  /// \returns A pointer to the type, or \c nullptr if none was found.
  LLVM_ABI const BTF::CommonType *findType(uint32_t Id) const;

  /// Count the BTF types stored in this parser.
  ///
  /// \returns The total number of known BTF types.
  size_t typesCount() const { return Types.size(); }

  /// Options that select which BTF subsections to load.
  struct ParseOptions {
    /// Load instruction-to-source line mappings from .BTF.ext.
    bool LoadLines = false;
    /// Load the BTF type table from .BTF.
    bool LoadTypes = false;
    /// Load CO-RE field relocations from .BTF.ext.
    bool LoadRelocs = false;
  };

  /// Parse .BTF and .BTF.ext sections of \p Obj using \p Opts.
  ///
  /// Fills this instance with information stored in .BTF and .BTF.ext sections
  /// of \p Obj. If this instance was already filled, old data is discarded.
  ///
  /// If information cannot be parsed:
  /// - return an error describing the failure;
  /// - state of the BTFParser might be incomplete but is not invalid,
  ///   queries might be run against it, but some (or all) information
  ///   might be unavailable;
  ///
  /// \param Obj Object file that contains the .BTF and .BTF.ext sections.
  /// \param Opts Subsections to load (lines, types, and relocations).
  /// \returns Success, or an error describing why parsing failed.
  LLVM_ABI Error parse(const ObjectFile &Obj, const ParseOptions &Opts);
  /// Parse .BTF and .BTF.ext sections of \p Obj, loading all subsections.
  ///
  /// Equivalent to \c parse(Obj, {true, true, true}).
  ///
  /// \param Obj Object file that contains the .BTF and .BTF.ext sections.
  /// \returns Success, or an error describing why parsing failed.
  Error parse(const ObjectFile &Obj) { return parse(Obj, {true, true, true}); }

  /// Check whether \p Obj has both .BTF and .BTF.ext sections.
  ///
  /// \param Obj Object file to inspect.
  /// \returns True if both sections are present.
  LLVM_ABI static bool hasBTFSections(const ObjectFile &Obj);
};

} // namespace llvm

#endif // LLVM_DEBUGINFO_BTF_BTFPARSER_H
