//===----------------------- View.h -----------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
/// \file
///
/// This file defines the main interface for Views. Each view contributes a
/// portion of the final report generated by the tool.
///
//===----------------------------------------------------------------------===//

#ifndef LLVM_MCA_VIEW_H
#define LLVM_MCA_VIEW_H

#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MCA/HWEventListener.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/raw_ostream.h"

namespace llvm {
namespace mca {

/// A view that contributes a portion of the MCA analysis report.
///
/// Views listen for hardware events during pipeline simulation and collect
/// statistics that are later printed or serialized as part of the final report
/// generated by the tool.
class LLVM_ABI View : public HWEventListener {
public:
  /// Destroy this view.
  ~View() override = default;

  /// Print this view's report contribution to \p OS.
  /// \param OS Stream that receives the formatted view output.
  virtual void printView(llvm::raw_ostream &OS) const = 0;
  /// Return the human-readable name of this view.
  /// \return The view name as a string reference.
  virtual StringRef getNameAsString() const = 0;

  /// Serialize this view's collected data as JSON.
  ///
  /// The default implementation returns a placeholder string indicating that
  /// JSON serialization is not implemented for this view.
  /// \return A JSON value representing this view's data, or a placeholder.
  virtual json::Value toJSON() const { return "not implemented"; }
  /// Return true if this view can be serialized to JSON.
  /// \return True if this view supports JSON serialization.
  virtual bool isSerializable() const { return true; }

  /// Provide a key function for this polymorphic base.
  void anchor() override;
};
} // namespace mca
} // namespace llvm

#endif
