//===- LLVMBitCodes.h - Enum values for the LLVM bitcode format -*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This header defines Bitcode enum values for LLVM IR bitcode files.
//
// The enum values defined in this file should be considered permanent.  If
// new features are added, they should have values added at the end of the
// respective lists.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_BITCODE_LLVMBITCODES_H
#define LLVM_BITCODE_LLVMBITCODES_H

// This is the only file included, and it, in turn, is a leaf header.
// This allows external tools to dump the AST of this file and analyze it for
// changes without needing to fully or partially build LLVM itself.
#include "llvm/Bitstream/BitCodeEnums.h"

namespace llvm {
/// Bitcode record and block code enumerations for LLVM IR bitcode files.
namespace bitc {
// The only top-level block types are MODULE, IDENTIFICATION, STRTAB and SYMTAB.
/// Top-level and nested block IDs used in LLVM IR bitcode files.
enum BlockIDs {
  /// MODULE block containing an LLVM IR module.
  MODULE_BLOCK_ID = FIRST_APPLICATION_BLOCKID,

  /// Parameter attribute set definitions.
  PARAMATTR_BLOCK_ID,
  /// Parameter attribute group definitions.
  PARAMATTR_GROUP_BLOCK_ID,

  /// Constant pool for a module or function.
  CONSTANTS_BLOCK_ID,
  /// Function body definitions.
  FUNCTION_BLOCK_ID,

  /// Block intended to contains information on the bitcode versioning.
  /// Can be used to provide better error messages when we fail to parse a
  /// bitcode file.
  IDENTIFICATION_BLOCK_ID,

  /// Value symbol table.
  VALUE_SYMTAB_BLOCK_ID,
  /// Metadata definitions.
  METADATA_BLOCK_ID,
  /// Metadata attachments to values.
  METADATA_ATTACHMENT_ID,

  /// Type table.
  TYPE_BLOCK_ID_NEW,

  /// Use-list order information.
  USELIST_BLOCK_ID,

  /// Module path symbol table (ThinLTO).
  MODULE_STRTAB_BLOCK_ID,
  /// Per-module or combined global value summaries (ThinLTO).
  GLOBALVAL_SUMMARY_BLOCK_ID,

  /// Operand bundle tag strings.
  OPERAND_BUNDLE_TAGS_BLOCK_ID,

  /// Metadata kind name table.
  METADATA_KIND_BLOCK_ID,

  /// Shared string table blob.
  STRTAB_BLOCK_ID,

  /// Full LTO global value summary block.
  FULL_LTO_GLOBALVAL_SUMMARY_BLOCK_ID,

  /// Symbol table blob.
  SYMTAB_BLOCK_ID,

  /// Synchronization scope name table.
  SYNC_SCOPE_NAMES_BLOCK_ID,
};

/// Identification block contains a string that describes the producer details,
/// and an epoch that defines the auto-upgrade capability.
enum IdentificationCodes {
  IDENTIFICATION_CODE_STRING = 1, ///< IDENTIFICATION: [strchr x N]
  IDENTIFICATION_CODE_EPOCH = 2,  ///< EPOCH: [epoch#]
};

/// The epoch that defines the auto-upgrade compatibility for the bitcode.
///
/// LLVM guarantees in a major release that a minor release can read bitcode
/// generated by previous minor releases. We translate this by making the reader
/// accepting only bitcode with the same epoch, except for the X.0 release which
/// also accepts N-1.
enum {
  BITCODE_CURRENT_EPOCH = 0 ///< Current bitcode auto-upgrade epoch value.
};

/// MODULE blocks have a number of optional fields and subblocks.
enum ModuleCodes {
  MODULE_CODE_VERSION = 1,     ///< VERSION: [version#]
  MODULE_CODE_TRIPLE = 2,      ///< TRIPLE: [strchr x N]
  MODULE_CODE_DATALAYOUT = 3,  ///< DATALAYOUT: [strchr x N]
  MODULE_CODE_ASM = 4,         ///< ASM: [strchr x N]
  MODULE_CODE_SECTIONNAME = 5, ///< SECTIONNAME: [strchr x N]

  // Deprecated, but still needed to read old bitcode files.
  MODULE_CODE_DEPLIB = 6, ///< DEPLIB: [strchr x N] (deprecated)

  /// GLOBALVAR: [pointer type, isconst, initid, linkage, alignment, section,
  /// visibility, threadlocal]
  MODULE_CODE_GLOBALVAR = 7,

  /// FUNCTION: [type, callingconv, isproto, linkage, paramattrs, alignment,
  /// section, visibility, gc, unnamed_addr]
  MODULE_CODE_FUNCTION = 8,

  /// ALIAS: [alias type, aliasee val#, linkage, visibility] (legacy encoding)
  MODULE_CODE_ALIAS_OLD = 9,

  MODULE_CODE_GCNAME = 11, ///< GCNAME: [strchr x N]
  MODULE_CODE_COMDAT = 12, ///< COMDAT: [selection_kind, name]

  MODULE_CODE_VSTOFFSET = 13, ///< VSTOFFSET: [offset]

  /// ALIAS: [alias value type, addrspace, aliasee val#, linkage, visibility]
  MODULE_CODE_ALIAS = 14,

  /// Unused metadata values record (reserved / unused).
  MODULE_CODE_METADATA_VALUES_UNUSED = 15,

  /// SOURCE_FILENAME: [namechar x N]
  MODULE_CODE_SOURCE_FILENAME = 16,

  /// HASH: [5*i32]
  MODULE_CODE_HASH = 17,

  /// IFUNC: [ifunc value type, addrspace, resolver val#, linkage, visibility]
  MODULE_CODE_IFUNC = 18,

  MODULE_CODE_ASM_PROPERTY = 19, ///< ASM property string: [strchr x N]

  /// GUIDLIST: [n x i64]
  MODULE_CODE_GUIDLIST = 20,
};

/// PARAMATTR blocks have code for defining a parameter attribute set.
enum AttributeCodes {
  // Deprecated, but still needed to read old bitcode files.
  /// ENTRY: [paramidx0, attr0, paramidx1, attr1...] (legacy encoding)
  PARAMATTR_CODE_ENTRY_OLD = 1,
  PARAMATTR_CODE_ENTRY = 2,    ///< ENTRY: [attrgrp0, attrgrp1, ...]
  PARAMATTR_GRP_CODE_ENTRY = 3 ///< ENTRY: [grpid, idx, attr0, attr1, ...]
};

/// TYPE blocks have codes for each type primitive they use.
enum TypeCodes {
  TYPE_CODE_NUMENTRY = 1, ///< NUMENTRY: [numentries]

  // Type Codes
  TYPE_CODE_VOID = 2,    ///< VOID
  TYPE_CODE_FLOAT = 3,   ///< FLOAT
  TYPE_CODE_DOUBLE = 4,  ///< DOUBLE
  TYPE_CODE_LABEL = 5,   ///< LABEL
  TYPE_CODE_OPAQUE = 6,  ///< OPAQUE
  TYPE_CODE_INTEGER = 7, ///< INTEGER: [width]
  TYPE_CODE_POINTER = 8, ///< POINTER: [pointee type]

  /// FUNCTION: [vararg, attrid, retty, paramty x N] (legacy encoding)
  TYPE_CODE_FUNCTION_OLD = 9,

  TYPE_CODE_HALF = 10, ///< HALF

  TYPE_CODE_ARRAY = 11,  ///< ARRAY: [numelts, eltty]
  TYPE_CODE_VECTOR = 12, ///< VECTOR: [numelts, eltty]

  // These are not with the other floating point types because they're
  // a late addition, and putting them in the right place breaks
  // binary compatibility.
  TYPE_CODE_X86_FP80 = 13,  ///< X86 LONG DOUBLE
  TYPE_CODE_FP128 = 14,     ///< LONG DOUBLE (112 bit mantissa)
  TYPE_CODE_PPC_FP128 = 15, ///< PPC LONG DOUBLE (2 doubles)

  TYPE_CODE_METADATA = 16, ///< METADATA

  TYPE_CODE_X86_MMX = 17, ///< X86 MMX

  TYPE_CODE_STRUCT_ANON = 18,  ///< STRUCT_ANON: [ispacked, eltty x N]
  TYPE_CODE_STRUCT_NAME = 19,  ///< STRUCT_NAME: [strchr x N]
  TYPE_CODE_STRUCT_NAMED = 20, ///< STRUCT_NAMED: [ispacked, eltty x N]

  TYPE_CODE_FUNCTION = 21, ///< FUNCTION: [vararg, retty, paramty x N]

  TYPE_CODE_TOKEN = 22, ///< TOKEN

  TYPE_CODE_BFLOAT = 23,  ///< BRAIN FLOATING POINT
  TYPE_CODE_X86_AMX = 24, ///< X86 AMX

  TYPE_CODE_OPAQUE_POINTER = 25, ///< OPAQUE_POINTER: [addrspace]

  TYPE_CODE_TARGET_TYPE = 26, ///< TARGET_TYPE

  TYPE_CODE_BYTE = 27, ///< BYTE: [width]
};

/// Operand bundle tag string table record codes.
enum OperandBundleTagCode {
  OPERAND_BUNDLE_TAG = 1, ///< TAG: [strchr x N]
};

/// Synchronization scope name table record codes.
enum SyncScopeNameCode {
  SYNC_SCOPE_NAME = 1, ///< Synchronization scope name string.
};

/// Value symbol table record codes.
enum ValueSymtabCodes {
  VST_CODE_ENTRY = 1,   ///< VST_ENTRY: [valueid, namechar x N]
  VST_CODE_BBENTRY = 2, ///< VST_BBENTRY: [bbid, namechar x N]
  VST_CODE_FNENTRY = 3, ///< VST_FNENTRY: [valueid, offset, namechar x N]
  /// VST_COMBINED_ENTRY: [valueid, refguid]
  VST_CODE_COMBINED_ENTRY = 5
};

/// Module path symbol table record codes (ThinLTO).
enum ModulePathSymtabCodes {
  MST_CODE_ENTRY = 1, ///< MST_ENTRY: [modid, namechar x N]
  MST_CODE_HASH = 2,  ///< MST_HASH: [5*i32]
};

/// Global value summary symbol table record codes for per-module and combined
/// ThinLTO indexes.
enum GlobalValueSummarySymtabCodes {
  /// PERMODULE: [valueid, flags, instcount, numrefs, numrefs x valueid,
  /// n x (valueid)]
  FS_PERMODULE = 1,
  /// PERMODULE_PROFILE: [valueid, flags, instcount, numrefs,
  /// numrefs x valueid, n x (valueid, hotness+tailcall)]
  FS_PERMODULE_PROFILE = 2,
  /// PERMODULE_GLOBALVAR_INIT_REFS: [valueid, flags, n x valueid]
  FS_PERMODULE_GLOBALVAR_INIT_REFS = 3,
  /// COMBINED: [valueid, modid, flags, instcount, numrefs, numrefs x valueid,
  /// n x (valueid)]
  FS_COMBINED = 4,
  /// COMBINED_PROFILE: [valueid, modid, flags, instcount, numrefs,
  /// numrefs x valueid, n x (valueid, hotness+tailcall)]
  FS_COMBINED_PROFILE = 5,
  /// COMBINED_GLOBALVAR_INIT_REFS: [valueid, modid, flags, n x valueid]
  FS_COMBINED_GLOBALVAR_INIT_REFS = 6,
  /// ALIAS: [valueid, flags, valueid]
  FS_ALIAS = 7,
  /// COMBINED_ALIAS: [valueid, modid, flags, valueid]
  FS_COMBINED_ALIAS = 8,
  /// COMBINED_ORIGINAL_NAME: [original_name_hash]
  FS_COMBINED_ORIGINAL_NAME = 9,
  /// VERSION of the summary, bumped when adding flags for instance.
  FS_VERSION = 10,
  /// The list of llvm.type.test type identifiers used by the following function
  /// that are used other than by an llvm.assume.
  /// [n x typeid]
  FS_TYPE_TESTS = 11,
  /// The list of virtual calls made by this function using
  /// llvm.assume(llvm.type.test) intrinsics that do not have all constant
  /// integer arguments.
  /// [n x (typeid, offset)]
  FS_TYPE_TEST_ASSUME_VCALLS = 12,
  /// The list of virtual calls made by this function using
  /// llvm.type.checked.load intrinsics that do not have all constant integer
  /// arguments.
  /// [n x (typeid, offset)]
  FS_TYPE_CHECKED_LOAD_VCALLS = 13,
  /// Identifies a virtual call made by this function using an
  /// llvm.assume(llvm.type.test) intrinsic with all constant integer arguments.
  /// [typeid, offset, n x arg]
  FS_TYPE_TEST_ASSUME_CONST_VCALL = 14,
  /// Identifies a virtual call made by this function using an
  /// llvm.type.checked.load intrinsic with all constant integer arguments.
  /// [typeid, offset, n x arg]
  FS_TYPE_CHECKED_LOAD_CONST_VCALL = 15,
  /// Assigns a GUID to a value ID. This normally appears only in combined
  /// summaries, but it can also appear in per-module summaries for PGO data.
  /// [valueid, guid]
  FS_VALUE_GUID = 16,
  /// The list of local functions with CFI jump tables. Function names are
  /// strings in strtab.
  /// [n * name]
  FS_CFI_FUNCTION_DEFS = 17,
  /// The list of external functions with CFI jump tables. Function names are
  /// strings in strtab.
  /// [n * name]
  FS_CFI_FUNCTION_DECLS = 18,
  /// Deprecated per-module summary that also adds relative block frequency to
  /// callee info.
  /// PERMODULE_RELBF: [valueid, flags, instcount, numrefs, numrefs x valueid,
  /// n x (valueid, relblockfreq+tailcall)]
  FS_PERMODULE_RELBF = 19,
  /// Index-wide flags.
  FS_FLAGS = 20,
  /// Maps type identifier to summary information for that type identifier.
  /// Produced by the thin link (only lives in combined index).
  /// TYPE_ID: [typeid, kind, bitwidth, align, size, bitmask, inlinebits,
  /// n x (typeid, kind, name, numrba,
  /// numrba x (numarg, numarg x arg, kind, info, byte, bit))]
  FS_TYPE_ID = 21,
  /// For background see overview at https://llvm.org/docs/TypeMetadata.html.
  /// The type metadata includes both the type identifier and the offset of
  /// the address point of the type (the address held by objects of that type
  /// which may not be the beginning of the virtual table). Vtable definitions
  /// are decorated with type metadata for the types they are compatible with.
  ///
  /// Maps type identifier to summary information for that type identifier
  /// computed from type metadata: the valueid of each vtable definition
  /// decorated with a type metadata for that identifier, and the offset from
  /// the corresponding type metadata.
  /// Exists in the per-module summary to provide information to thin link
  /// for index-based whole program devirtualization.
  /// TYPE_ID_METADATA: [typeid, n x (valueid, offset)]
  FS_TYPE_ID_METADATA = 22,
  /// Summarizes vtable definition for use in index-based whole program
  /// devirtualization during the thin link.
  /// PERMODULE_VTABLE_GLOBALVAR_INIT_REFS: [valueid, flags, varflags,
  /// numrefs, numrefs x valueid, n x (valueid, offset)]
  FS_PERMODULE_VTABLE_GLOBALVAR_INIT_REFS = 23,
  /// The total number of basic blocks in the module.
  FS_BLOCK_COUNT = 24,
  /// Range information for accessed offsets for every argument.
  /// [n x (paramno, range, numcalls, numcalls x (callee_guid, paramno, range))]
  FS_PARAM_ACCESS = 25,
  /// Summary of per-module memprof callsite metadata.
  /// [valueid, n x stackidindex]
  FS_PERMODULE_CALLSITE_INFO = 26,
  /// Summary of per-module allocation memprof metadata.
  /// [nummib, nummib x (alloc type, context radix tree index),
  /// [nummib x (numcontext x total size)]?]
  FS_PERMODULE_ALLOC_INFO = 27,
  /// Summary of combined index memprof callsite metadata.
  /// [valueid, numstackindices, numver,
  /// numstackindices x stackidindex, numver x version]
  FS_COMBINED_CALLSITE_INFO = 28,
  /// Summary of combined index allocation memprof metadata.
  /// [nummib, numver, nummib x (alloc type, context radix tree index),
  /// numver x version]
  FS_COMBINED_ALLOC_INFO = 29,
  /// List of all stack ids referenced by index in the callsite and alloc infos.
  /// [n x stack id]
  FS_STACK_IDS = 30,
  /// List of all full stack id pairs corresponding to the total sizes recorded
  /// at the end of the alloc info when reporting of hinted bytes is enabled.
  /// We use a fixed-width array, which is more efficient as these ids typically
  /// are close to 64 bits in size. The max fixed width value supported is 32
  /// bits so each 64-bit context id hash is recorded as a pair (upper 32 bits
  /// first). This record must immediately precede the associated alloc info, and
  /// the entries must be in the exact same order as the corresponding sizes.
  /// [nummib x (numcontext x full stack id)]
  FS_ALLOC_CONTEXT_IDS = 31,
  /// Linearized radix tree of allocation contexts. See the description above the
  /// CallStackRadixTreeBuilder class in ProfileData/MemProf.h for format.
  /// [n x entry]
  FS_CONTEXT_RADIX_TREE_ARRAY = 32,
  /// Summary of combined index allocation memprof metadata, without context.
  /// [nummib, numver, nummib x alloc type, numver x version]
  FS_COMBINED_ALLOC_INFO_NO_CONTEXT = 33,
};

/// Metadata block record codes for debug and other metadata nodes.
enum MetadataCodes {
  METADATA_STRING_OLD = 1,     ///< MDSTRING: [values]
  METADATA_VALUE = 2,          ///< VALUE: [type num, value num]
  METADATA_NODE = 3,           ///< NODE: [n x md num]
  METADATA_NAME = 4,           ///< STRING: [values]
  METADATA_DISTINCT_NODE = 5,  ///< DISTINCT_NODE: [n x md num]
  METADATA_KIND = 6,           ///< [n x [id, name]]
  METADATA_LOCATION = 7,       ///< [distinct, line, col, scope, inlined-at?]
  METADATA_OLD_NODE = 8,       ///< OLD_NODE: [n x (type num, value num)]
  METADATA_OLD_FN_NODE = 9,    ///< OLD_FN_NODE: [n x (type num, value num)]
  METADATA_NAMED_NODE = 10,    ///< NAMED_NODE: [n x mdnodes]
  METADATA_ATTACHMENT = 11,    ///< [m x [value, [n x [id, mdnode]]]
  METADATA_GENERIC_DEBUG = 12, ///< [distinct, tag, vers, header, n x md num]
  METADATA_SUBRANGE = 13,      ///< [distinct, count, lo]
  METADATA_ENUMERATOR = 14,    ///< [isUnsigned|distinct, value, name]
  METADATA_BASIC_TYPE = 15,    ///< [distinct, tag, name, size, align, enc]
  METADATA_FILE = 16, ///< [distinct, filename, directory, checksumkind, checksum]
  METADATA_DERIVED_TYPE = 17,       ///< [distinct, ...]
  METADATA_COMPOSITE_TYPE = 18,     ///< [distinct, ...]
  METADATA_SUBROUTINE_TYPE = 19,    ///< [distinct, flags, types, cc]
  METADATA_COMPILE_UNIT = 20,       ///< [distinct, ...]
  METADATA_SUBPROGRAM = 21,         ///< [distinct, ...]
  METADATA_LEXICAL_BLOCK = 22,      ///< [distinct, scope, file, line, column]
  METADATA_LEXICAL_BLOCK_FILE = 23, ///< [distinct, scope, file, discriminator]
  METADATA_NAMESPACE = 24, ///< [distinct, scope, file, name, line, exportSymbols]
  METADATA_TEMPLATE_TYPE = 25,   ///< [distinct, scope, name, type, ...]
  METADATA_TEMPLATE_VALUE = 26,  ///< [distinct, scope, name, type, value, ...]
  METADATA_GLOBAL_VAR = 27,      ///< [distinct, ...]
  METADATA_LOCAL_VAR = 28,       ///< [distinct, ...]
  METADATA_EXPRESSION = 29,      ///< [distinct, n x element]
  METADATA_OBJC_PROPERTY = 30,   ///< [distinct, name, file, line, ...]
  METADATA_IMPORTED_ENTITY = 31, ///< [distinct, tag, scope, entity, line, name]
  METADATA_MODULE = 32,          ///< [distinct, scope, name, ...]
  METADATA_MACRO = 33,           ///< [distinct, macinfo, line, name, value]
  METADATA_MACRO_FILE = 34,      ///< [distinct, macinfo, line, file, ...]
  METADATA_STRINGS = 35,         ///< [count, offset] blob([lengths][chars])
  METADATA_GLOBAL_DECL_ATTACHMENT = 36, ///< [valueid, n x [id, mdnode]]
  METADATA_GLOBAL_VAR_EXPR = 37,        ///< [distinct, var, expr]
  METADATA_INDEX_OFFSET = 38,           ///< [offset]
  METADATA_INDEX = 39,                  ///< [bitpos]
  METADATA_LABEL = 40,                  ///< [distinct, scope, name, file, line]
  METADATA_STRING_TYPE = 41,            ///< [distinct, name, size, align,...]
  // Codes 42 and 43 are reserved for support for Fortran array specific debug
  // info.
  METADATA_COMMON_BLOCK = 44,     ///< [distinct, scope, name, variable,...]
  METADATA_GENERIC_SUBRANGE = 45, ///< [distinct, count, lo, up, stride]
  METADATA_ARG_LIST = 46,         ///< [n x [type num, value num]]
  METADATA_ASSIGN_ID = 47,        ///< [distinct, ...]
  METADATA_SUBRANGE_TYPE = 48,    ///< [distinct, ...]
  METADATA_FIXED_POINT_TYPE = 49, ///< [distinct, ...]
  METADATA_PROPERTY = 50, ///< [distinct, name, file, line, type, backing_storage]
};

/// Constants block record codes for constant emission with an implicit current
/// type.
enum ConstantsCodes {
  CST_CODE_SETTYPE = 1,          ///< SETTYPE: [typeid]
  CST_CODE_NULL = 2,             ///< NULL
  CST_CODE_UNDEF = 3,            ///< UNDEF
  CST_CODE_INTEGER = 4,          ///< INTEGER: [intval]
  CST_CODE_WIDE_INTEGER = 5,     ///< WIDE_INTEGER: [n x intval]
  CST_CODE_FLOAT = 6,            ///< FLOAT: [fpval]
  CST_CODE_AGGREGATE = 7,        ///< AGGREGATE: [n x value number]
  CST_CODE_STRING = 8,           ///< STRING: [values]
  CST_CODE_CSTRING = 9,          ///< CSTRING: [values]
  CST_CODE_CE_BINOP = 10,        ///< CE_BINOP: [opcode, opval, opval]
  CST_CODE_CE_CAST = 11,         ///< CE_CAST: [opcode, opty, opval]
  CST_CODE_CE_GEP_OLD = 12,      ///< CE_GEP: [n x operands]
  CST_CODE_CE_SELECT = 13,       ///< CE_SELECT: [opval, opval, opval]
  CST_CODE_CE_EXTRACTELT = 14,   ///< CE_EXTRACTELT: [opty, opval, opval]
  CST_CODE_CE_INSERTELT = 15,    ///< CE_INSERTELT: [opval, opval, opval]
  CST_CODE_CE_SHUFFLEVEC = 16,   ///< CE_SHUFFLEVEC: [opval, opval, opval]
  CST_CODE_CE_CMP = 17,          ///< CE_CMP: [opty, opval, opval, pred]
  CST_CODE_INLINEASM_OLD = 18,   ///< INLINEASM: [sideeffect|alignstack, asmstr, conststr]
  CST_CODE_CE_SHUFVEC_EX = 19,   ///< SHUFVEC_EX: [opty, opval, opval, opval]
  CST_CODE_CE_INBOUNDS_GEP = 20, ///< INBOUNDS_GEP: [n x operands]
  CST_CODE_BLOCKADDRESS = 21,    ///< BLOCKADDRESS: [fnty, fnval, bb#]
  CST_CODE_DATA = 22,            ///< DATA: [n x elements]
  CST_CODE_INLINEASM_OLD2 = 23,  ///< INLINEASM: [sideeffect|alignstack|asmdialect, asmstr, conststr]
  CST_CODE_CE_GEP_WITH_INRANGE_INDEX_OLD = 24, ///< [opty, flags, n x operands]
  CST_CODE_CE_UNOP = 25,                       ///< CE_UNOP: [opcode, opval]
  CST_CODE_POISON = 26,                        ///< POISON
  CST_CODE_DSO_LOCAL_EQUIVALENT = 27, ///< DSO_LOCAL_EQUIVALENT: [gvty, gv]
  CST_CODE_INLINEASM_OLD3 = 28, ///< INLINEASM: [sideeffect|alignstack|asmdialect|unwind, asmstr, conststr]
  CST_CODE_NO_CFI_VALUE = 29,   ///< NO_CFI: [fty, f]
  CST_CODE_INLINEASM = 30, ///< INLINEASM: [fnty, sideeffect|alignstack|asmdialect|unwind, asmstr, conststr]
  CST_CODE_CE_GEP_WITH_INRANGE = 31, ///< [opty, flags, range, n x operands]
  CST_CODE_CE_GEP = 32,              ///< [opty, flags, n x operands]
  CST_CODE_PTRAUTH = 33,             ///< [ptr, key, disc, addrdisc]
  CST_CODE_PTRAUTH2 = 34, ///< [ptr, key, disc, addrdisc, deactivation_symbol]
  CST_CODE_BYTE = 35,      ///< BYTE: [intval]
  CST_CODE_WIDE_BYTE = 36, ///< WIDE_BYTE: [n x intval]
};

/// Bitcode encodings for cast opcodes in CST_CODE_CE_CAST and related records.
///
/// The values of these enums have no fixed relation to the LLVM IR enum values.
/// Changing these will break compatibility with old files.
enum CastOpcodes {
  CAST_TRUNC = 0,         ///< Truncate integer cast.
  CAST_ZEXT = 1,          ///< Zero-extend integer cast.
  CAST_SEXT = 2,          ///< Sign-extend integer cast.
  CAST_FPTOUI = 3,        ///< Floating-point to unsigned integer cast.
  CAST_FPTOSI = 4,        ///< Floating-point to signed integer cast.
  CAST_UITOFP = 5,        ///< Unsigned integer to floating-point cast.
  CAST_SITOFP = 6,        ///< Signed integer to floating-point cast.
  CAST_FPTRUNC = 7,       ///< Floating-point truncate cast.
  CAST_FPEXT = 8,         ///< Floating-point extend cast.
  CAST_PTRTOINT = 9,      ///< Pointer to integer cast.
  CAST_INTTOPTR = 10,     ///< Integer to pointer cast.
  CAST_BITCAST = 11,      ///< Bitcast.
  CAST_ADDRSPACECAST = 12, ///< Address-space cast.
  CAST_PTRTOADDR = 13,    ///< Pointer to address cast.
};

/// Bitcode encodings for unary opcodes in CST_CODE_CE_UNOP and related records.
///
/// The values of these enums have no fixed relation to the LLVM IR enum values.
/// Changing these will break compatibility with old files.
enum UnaryOpcodes {
  UNOP_FNEG = 0 ///< Floating-point negation.
};

/// Bitcode encodings for binary opcodes in CST_CODE_CE_BINOP and related records.
///
/// The values of these enums have no fixed relation to the LLVM IR enum values.
/// Changing these will break compatibility with old files.
enum BinaryOpcodes {
  BINOP_ADD = 0,  ///< Addition.
  BINOP_SUB = 1,  ///< Subtraction.
  BINOP_MUL = 2,  ///< Multiplication.
  BINOP_UDIV = 3, ///< Unsigned division.
  BINOP_SDIV = 4, ///< Signed division (also overloaded for FP).
  BINOP_UREM = 5, ///< Unsigned remainder.
  BINOP_SREM = 6, ///< Signed remainder (also overloaded for FP).
  BINOP_SHL = 7,  ///< Shift left.
  BINOP_LSHR = 8, ///< Logical shift right.
  BINOP_ASHR = 9, ///< Arithmetic shift right.
  BINOP_AND = 10, ///< Bitwise AND.
  BINOP_OR = 11,  ///< Bitwise OR.
  BINOP_XOR = 12  ///< Bitwise XOR.
};

/// Bitcode encodings for AtomicRMW operations.
///
/// The values of these enums have no fixed relation to the LLVM IR enum values.
/// Changing these will break compatibility with old files.
enum RMWOperations {
  RMW_XCHG = 0,         ///< Atomic exchange.
  RMW_ADD = 1,          ///< Atomic add.
  RMW_SUB = 2,          ///< Atomic subtract.
  RMW_AND = 3,          ///< Atomic bitwise AND.
  RMW_NAND = 4,         ///< Atomic bitwise NAND.
  RMW_OR = 5,           ///< Atomic bitwise OR.
  RMW_XOR = 6,          ///< Atomic bitwise XOR.
  RMW_MAX = 7,          ///< Atomic signed maximum.
  RMW_MIN = 8,          ///< Atomic signed minimum.
  RMW_UMAX = 9,         ///< Atomic unsigned maximum.
  RMW_UMIN = 10,        ///< Atomic unsigned minimum.
  RMW_FADD = 11,        ///< Atomic floating-point add.
  RMW_FSUB = 12,        ///< Atomic floating-point subtract.
  RMW_FMAX = 13,        ///< Atomic floating-point maximum.
  RMW_FMIN = 14,        ///< Atomic floating-point minimum.
  RMW_UINC_WRAP = 15,   ///< Atomic unsigned increment with wrap.
  RMW_UDEC_WRAP = 16,   ///< Atomic unsigned decrement with wrap.
  RMW_USUB_COND = 17,   ///< Atomic unsigned conditional subtract.
  RMW_USUB_SAT = 18,    ///< Atomic unsigned saturating subtract.
  RMW_FMAXIMUM = 19,    ///< Atomic floating-point maximum (IEEE).
  RMW_FMINIMUM = 20,    ///< Atomic floating-point minimum (IEEE).
  RMW_FMAXIMUMNUM = 21, ///< Atomic floating-point maximum number.
  RMW_FMINIMUMNUM = 22, ///< Atomic floating-point minimum number.
};

/// Flags for AtomicRMW operation records in bitcode.
enum RMWOperationFlags {
  RMW_ELEMENTWISE_FLAG = 1 << 5, ///< Elementwise AtomicRMW flag bit.
};

/// OverflowingBinaryOperatorOptionalFlags - Flags for serializing
/// OverflowingBinaryOperator's SubclassOptionalData contents.
enum OverflowingBinaryOperatorOptionalFlags {
  OBO_NO_UNSIGNED_WRAP = 0, ///< No unsigned wrap (nuw) flag.
  OBO_NO_SIGNED_WRAP = 1    ///< No signed wrap (nsw) flag.
};

/// TruncInstOptionalFlags - Flags for serializing
/// TruncInstOptionalFlags's SubclassOptionalData contents.
enum TruncInstOptionalFlags {
  TIO_NO_UNSIGNED_WRAP = 0, ///< Truncation no unsigned wrap flag.
  TIO_NO_SIGNED_WRAP = 1    ///< Truncation no signed wrap flag.
};

/// FastMath Flags
/// This is a fixed layout derived from the bitcode emitted by LLVM 5.0
/// intended to decouple the in-memory representation from the serialization.
enum FastMathMap {
  UnsafeAlgebra = (1 << 0),   ///< Legacy unsafe-algebra fast-math flag.
  NoNaNs = (1 << 1),          ///< Assume no NaN results or arguments.
  NoInfs = (1 << 2),          ///< Assume no infinite results or arguments.
  NoSignedZeros = (1 << 3),   ///< Ignore the sign of zero.
  AllowReciprocal = (1 << 4), ///< Allow reciprocal transformations.
  AllowContract = (1 << 5),   ///< Allow floating-point contraction.
  ApproxFunc = (1 << 6),      ///< Allow approximate function results.
  AllowReassoc = (1 << 7)     ///< Allow reassociation of floating-point ops.
};

/// Flags for serializing PossiblyNonNegInst's SubclassOptionalData contents.
enum PossiblyNonNegInstOptionalFlags {
  PNNI_NON_NEG = 0 ///< Non-negative (nneg) flag.
};

/// PossiblyExactOperatorOptionalFlags - Flags for serializing
/// PossiblyExactOperator's SubclassOptionalData contents.
enum PossiblyExactOperatorOptionalFlags {
  PEO_EXACT = 0 ///< Exact division/shift flag.
};

/// PossiblyDisjointInstOptionalFlags - Flags for serializing
/// PossiblyDisjointInst's SubclassOptionalData contents.
enum PossiblyDisjointInstOptionalFlags {
  PDI_DISJOINT = 0 ///< Disjoint OR flag.
};

/// Mark to distinguish metadata from value in an operator bundle.
enum MetadataOperandBundleValueMarker {
  OB_METADATA = 0x80000000 ///< High bit marking a metadata operand-bundle value.
};

/// GetElementPtrOptionalFlags - Flags for serializing
/// GEPOperator's SubclassOptionalData contents.
enum GetElementPtrOptionalFlags {
  GEP_INBOUNDS = 0, ///< Inbounds GEP flag.
  GEP_NUSW = 1,     ///< No unsigned signed wrap (nusw) GEP flag.
  GEP_NUW = 2,      ///< No unsigned wrap (nuw) GEP flag.
};

/// ICmpOptionalFlags - Flags for serializing
/// ICmpOptionalFlags's SubclassOptionalData contents.
enum ICmpOptionalFlags {
  ICMP_SAME_SIGN = 0 ///< Same-sign icmp flag.
};

/// Encoded AtomicOrdering values.
enum AtomicOrderingCodes {
  ORDERING_NOTATOMIC = 0, ///< Not an atomic memory operation.
  ORDERING_UNORDERED = 1, ///< Unordered atomic ordering.
  ORDERING_MONOTONIC = 2, ///< Monotonic atomic ordering.
  ORDERING_ACQUIRE = 3,   ///< Acquire atomic ordering.
  ORDERING_RELEASE = 4,   ///< Release atomic ordering.
  ORDERING_ACQREL = 5,    ///< Acquire-release atomic ordering.
  ORDERING_SEQCST = 6     ///< Sequentially consistent atomic ordering.
};

/// Markers and flags for call instruction.
enum CallMarkersFlags {
  CALL_TAIL = 0,           ///< Tail call marker bit.
  CALL_CCONV = 1,          ///< Calling-convention encoding start bit.
  CALL_MUSTTAIL = 14,      ///< Must-tail call marker bit.
  CALL_EXPLICIT_TYPE = 15, ///< Explicit callee type present marker bit.
  CALL_NOTAIL = 16,        ///< Notail call marker bit.
  CALL_FMF = 17 ///< Call has optional fast-math-flags.
};

/// Function body block record codes for instructions and related records.
enum FunctionCodes {
  FUNC_CODE_DECLAREBLOCKS = 1, ///< DECLAREBLOCKS: [n]

  FUNC_CODE_INST_BINOP = 2,      ///< BINOP: [opcode, ty, opval, opval]
  FUNC_CODE_INST_CAST = 3,       ///< CAST: [opcode, ty, opty, opval]
  FUNC_CODE_INST_GEP_OLD = 4,    ///< GEP: [n x operands]
  FUNC_CODE_INST_SELECT = 5,     ///< SELECT: [ty, opval, opval, opval]
  FUNC_CODE_INST_EXTRACTELT = 6, ///< EXTRACTELT: [opty, opval, opval]
  FUNC_CODE_INST_INSERTELT = 7,  ///< INSERTELT: [ty, opval, opval, opval]
  FUNC_CODE_INST_SHUFFLEVEC = 8, ///< SHUFFLEVEC: [ty, opval, opval, opval]
  FUNC_CODE_INST_CMP = 9,        ///< CMP: [opty, opval, opval, pred]

  FUNC_CODE_INST_RET = 10,    ///< RET: [opty,opval<both optional>]
  FUNC_CODE_INST_BR = 11,     ///< BR: [bb#, bb#, cond] or [bb#]
  FUNC_CODE_INST_SWITCH = 12, ///< SWITCH: [opty, op0, op1, ...]
  FUNC_CODE_INST_INVOKE = 13, ///< INVOKE: [attr, fnty, op0,op1, ...]
  // 14 is unused.
  FUNC_CODE_INST_UNREACHABLE = 15, ///< UNREACHABLE

  FUNC_CODE_INST_PHI = 16, ///< PHI: [ty, val0,bb0, ...]
  // 17 is unused.
  // 18 is unused.
  FUNC_CODE_INST_ALLOCA = 19, ///< ALLOCA: [instty, opty, op, align]
  FUNC_CODE_INST_LOAD = 20,   ///< LOAD: [opty, op, align, vol]
  // 21 is unused.
  // 22 is unused.
  FUNC_CODE_INST_VAARG = 23, ///< VAARG: [valistty, valist, instty]
  /// STORE encoding the pointer type so address-space info is retained.
  FUNC_CODE_INST_STORE_OLD = 24, // STORE: [ptrty,ptr,val, align, vol]
  // 25 is unused.
  FUNC_CODE_INST_EXTRACTVAL = 26, ///< EXTRACTVAL: [n x operands]
  FUNC_CODE_INST_INSERTVAL = 27,  ///< INSERTVAL: [n x operands]
  /// fcmp/icmp returning Int1TY or vector of Int1Ty. Same as CMP, exists to
  /// support legacy vicmp/vfcmp instructions.
  FUNC_CODE_INST_CMP2 = 28, // CMP2: [opty, opval, opval, pred]
  /// New select on i1 or [N x i1].
  FUNC_CODE_INST_VSELECT = 29, // VSELECT: [ty,opval,opval,predty,pred]
  FUNC_CODE_INST_INBOUNDS_GEP_OLD = 30, ///< INBOUNDS_GEP: [n x operands]
  FUNC_CODE_INST_INDIRECTBR = 31,       ///< INDIRECTBR: [opty, op0, op1, ...]
  // 32 is unused.
  FUNC_CODE_DEBUG_LOC_AGAIN = 33, ///< DEBUG_LOC_AGAIN

  FUNC_CODE_INST_CALL = 34, ///< CALL: [attr, cc, fnty, fnid, args...]

  FUNC_CODE_DEBUG_LOC = 35,          ///< DEBUG_LOC: [Line,Col,ScopeVal, IAVal]
  FUNC_CODE_INST_FENCE = 36,         ///< FENCE: [ordering, syncscope]
  FUNC_CODE_INST_CMPXCHG_OLD = 37,   ///< CMPXCHG: [ptrty, ptr, cmp, val, vol, ordering, syncscope, failure_ordering?, weak?]
  FUNC_CODE_INST_ATOMICRMW_OLD = 38, ///< ATOMICRMW: [ptrty,ptr,val, operation, align, vol, ordering, syncscope]
  FUNC_CODE_INST_RESUME = 39,        ///< RESUME: [opval]
  FUNC_CODE_INST_LANDINGPAD_OLD = 40, ///< LANDINGPAD: [ty,val,val,num,id0,val0...]
  FUNC_CODE_INST_LOADATOMIC = 41, ///< LOAD: [opty, op, align, vol, ordering, syncscope]
  FUNC_CODE_INST_STOREATOMIC_OLD = 42, ///< STORE: [ptrty,ptr,val, align, vol, ordering, syncscope]
  FUNC_CODE_INST_GEP = 43,             ///< GEP: [inbounds, n x operands]
  FUNC_CODE_INST_STORE = 44,       ///< STORE: [ptrty,ptr,valty,val, align, vol]
  FUNC_CODE_INST_STOREATOMIC = 45, ///< STORE: [ptrty,ptr,val, align, vol
  FUNC_CODE_INST_CMPXCHG = 46,     ///< CMPXCHG: [ptrty, ptr, cmp, val, vol, success_ordering, syncscope, failure_ordering, weak]
  FUNC_CODE_INST_LANDINGPAD = 47,  ///< LANDINGPAD: [ty,val,num,id0,val0...]
  FUNC_CODE_INST_CLEANUPRET = 48,  ///< CLEANUPRET: [val] or [val,bb#]
  FUNC_CODE_INST_CATCHRET = 49,    ///< CATCHRET: [val,bb#]
  FUNC_CODE_INST_CATCHPAD = 50,    ///< CATCHPAD: [bb#,bb#,num,args...]
  FUNC_CODE_INST_CLEANUPPAD = 51,  ///< CLEANUPPAD: [num,args...]
  FUNC_CODE_INST_CATCHSWITCH = 52, ///< CATCHSWITCH: [num,args...] or [num,args...,bb]
  // 53 is unused.
  // 54 is unused.
  FUNC_CODE_OPERAND_BUNDLE = 55,  ///< OPERAND_BUNDLE: [tag#, value...]
  FUNC_CODE_INST_UNOP = 56,       ///< UNOP: [opcode, ty, opval]
  FUNC_CODE_INST_CALLBR = 57,     ///< CALLBR: [attr, cc, norm, transfs, fnty, fnid, args...]
  FUNC_CODE_INST_FREEZE = 58,     ///< FREEZE: [opty, opval]
  FUNC_CODE_INST_ATOMICRMW = 59,  ///< ATOMICRMW: [ptrty, ptr, valty, val, operation, align, vol, ordering, syncscope]
  FUNC_CODE_BLOCKADDR_USERS = 60, ///< BLOCKADDR_USERS: [value...]

  FUNC_CODE_DEBUG_RECORD_VALUE = 61, ///< [DILocation, DILocalVariable, DIExpression, ValueAsMetadata]
  FUNC_CODE_DEBUG_RECORD_DECLARE = 62, ///< [DILocation, DILocalVariable, DIExpression, ValueAsMetadata]
  FUNC_CODE_DEBUG_RECORD_ASSIGN = 63, ///< [DILocation, DILocalVariable, DIExpression, ValueAsMetadata, DIAssignID, DIExpression (addr), ValueAsMetadata (addr)]
  FUNC_CODE_DEBUG_RECORD_VALUE_SIMPLE = 64, ///< [DILocation, DILocalVariable, DIExpression, Value]
  FUNC_CODE_DEBUG_RECORD_LABEL = 65, ///< [DILocation, DILabel]
  FUNC_CODE_DEBUG_RECORD_DECLARE_VALUE = 66, ///< [DILocation, DILocalVariable, DIExpression, ValueAsMetadata]
};

/// Use-list order block record codes.
enum UseListCodes {
  USELIST_CODE_DEFAULT = 1, ///< DEFAULT: [index..., value-id]
  USELIST_CODE_BB = 2       ///< BB: [index..., bb-id]
};

/// Encoded LLVM IR attribute kinds used in parameter attribute records.
enum AttributeKindCodes {
  // = 0 is unused
  ATTR_KIND_ALIGNMENT = 1,                          ///< alignment
  ATTR_KIND_ALWAYS_INLINE = 2,                      ///< alwaysinline
  ATTR_KIND_BY_VAL = 3,                             ///< byval
  ATTR_KIND_INLINE_HINT = 4,                        ///< inlinehint
  ATTR_KIND_IN_REG = 5,                             ///< inreg
  ATTR_KIND_MIN_SIZE = 6,                           ///< minsize
  ATTR_KIND_NAKED = 7,                              ///< naked
  ATTR_KIND_NEST = 8,                               ///< nest
  ATTR_KIND_NO_ALIAS = 9,                           ///< noalias
  ATTR_KIND_NO_BUILTIN = 10,                        ///< nobuiltin
  ATTR_KIND_NO_CAPTURE = 11,                        ///< nocapture
  ATTR_KIND_NO_DUPLICATE = 12,                      ///< noduplicate
  ATTR_KIND_NO_IMPLICIT_FLOAT = 13,                 ///< noimplicitfloat
  ATTR_KIND_NO_INLINE = 14,                         ///< noinline
  ATTR_KIND_NON_LAZY_BIND = 15,                     ///< nonlazybind
  ATTR_KIND_NO_RED_ZONE = 16,                       ///< noredzone
  ATTR_KIND_NO_RETURN = 17,                         ///< noreturn
  ATTR_KIND_NO_UNWIND = 18,                         ///< nounwind
  ATTR_KIND_OPTIMIZE_FOR_SIZE = 19,                 ///< optsize
  ATTR_KIND_READ_NONE = 20,                         ///< readnone
  ATTR_KIND_READ_ONLY = 21,                         ///< readonly
  ATTR_KIND_RETURNED = 22,                          ///< returned
  ATTR_KIND_RETURNS_TWICE = 23,                     ///< returns_twice
  ATTR_KIND_S_EXT = 24,                             ///< signext
  ATTR_KIND_STACK_ALIGNMENT = 25,                   ///< alignstack
  ATTR_KIND_STACK_PROTECT = 26,                     ///< ssp
  ATTR_KIND_STACK_PROTECT_REQ = 27,                 ///< sspreq
  ATTR_KIND_STACK_PROTECT_STRONG = 28,              ///< sspstrong
  ATTR_KIND_STRUCT_RET = 29,                        ///< sret
  ATTR_KIND_SANITIZE_ADDRESS = 30,                  ///< sanitize_address
  ATTR_KIND_SANITIZE_THREAD = 31,                   ///< sanitize_thread
  ATTR_KIND_SANITIZE_MEMORY = 32,                   ///< sanitize_memory
  ATTR_KIND_UW_TABLE = 33,                          ///< uwtable
  ATTR_KIND_Z_EXT = 34,                             ///< zeroext
  ATTR_KIND_BUILTIN = 35,                           ///< builtin
  ATTR_KIND_COLD = 36,                              ///< cold
  ATTR_KIND_OPTIMIZE_NONE = 37,                     ///< optnone
  ATTR_KIND_IN_ALLOCA = 38,                         ///< inalloca
  ATTR_KIND_NON_NULL = 39,                          ///< nonnull
  ATTR_KIND_JUMP_TABLE = 40,                        ///< jumptable
  ATTR_KIND_DEREFERENCEABLE = 41,                   ///< dereferenceable
  ATTR_KIND_DEREFERENCEABLE_OR_NULL = 42,           ///< dereferenceable_or_null
  ATTR_KIND_CONVERGENT = 43,                        ///< convergent
  ATTR_KIND_SAFESTACK = 44,                         ///< safestack
  ATTR_KIND_ARGMEMONLY = 45,                        ///< argmemonly
  ATTR_KIND_SWIFT_SELF = 46,                        ///< swiftself
  ATTR_KIND_SWIFT_ERROR = 47,                       ///< swifterror
  ATTR_KIND_NO_RECURSE = 48,                        ///< norecurse
  ATTR_KIND_INACCESSIBLEMEM_ONLY = 49,              ///< inaccessiblememonly
  ATTR_KIND_INACCESSIBLEMEM_OR_ARGMEMONLY = 50,     ///< inaccessiblemem_or_argmemonly
  ATTR_KIND_ALLOC_SIZE = 51,                        ///< allocsize
  ATTR_KIND_WRITEONLY = 52,                         ///< writeonly
  ATTR_KIND_SPECULATABLE = 53,                      ///< speculatable
  ATTR_KIND_STRICT_FP = 54,                         ///< strictfp
  ATTR_KIND_SANITIZE_HWADDRESS = 55,                ///< sanitize_hwaddress
  ATTR_KIND_NOCF_CHECK = 56,                        ///< nocf_check
  ATTR_KIND_OPT_FOR_FUZZING = 57,                   ///< optforfuzzing
  ATTR_KIND_SHADOWCALLSTACK = 58,                   ///< shadowcallstack
  ATTR_KIND_SPECULATIVE_LOAD_HARDENING = 59,        ///< speculative_load_hardening
  ATTR_KIND_IMMARG = 60,                            ///< immarg
  ATTR_KIND_WILLRETURN = 61,                        ///< willreturn
  ATTR_KIND_NOFREE = 62,                            ///< nofree
  ATTR_KIND_NOSYNC = 63,                            ///< nosync
  ATTR_KIND_SANITIZE_MEMTAG = 64,                   ///< sanitize_memtag
  ATTR_KIND_PREALLOCATED = 65,                      ///< preallocated
  ATTR_KIND_NO_MERGE = 66,                          ///< nomerge
  ATTR_KIND_NULL_POINTER_IS_VALID = 67,             ///< null_pointer_is_valid
  ATTR_KIND_NOUNDEF = 68,                           ///< noundef
  ATTR_KIND_BYREF = 69,                             ///< byref
  ATTR_KIND_MUSTPROGRESS = 70,                      ///< mustprogress
  ATTR_KIND_NO_CALLBACK = 71,                       ///< nocallback
  ATTR_KIND_HOT = 72,                               ///< hot
  ATTR_KIND_NO_PROFILE = 73,                        ///< noprofile
  ATTR_KIND_VSCALE_RANGE = 74,                      ///< vscale_range
  ATTR_KIND_SWIFT_ASYNC = 75,                       ///< swiftasync
  ATTR_KIND_NO_SANITIZE_COVERAGE = 76,              ///< nosanitize_coverage
  ATTR_KIND_ELEMENTTYPE = 77,                       ///< elementtype
  ATTR_KIND_DISABLE_SANITIZER_INSTRUMENTATION = 78, ///< disable_sanitizer_instrumentation
  ATTR_KIND_NO_SANITIZE_BOUNDS = 79,                ///< nosanitize_bounds
  ATTR_KIND_ALLOC_ALIGN = 80,                       ///< allocalign
  ATTR_KIND_ALLOCATED_POINTER = 81,                 ///< allocatedpointer
  ATTR_KIND_ALLOC_KIND = 82,                        ///< allockind
  ATTR_KIND_PRESPLIT_COROUTINE = 83,                ///< presplitcoroutine
  ATTR_KIND_FNRETTHUNK_EXTERN = 84,                 ///< fn_ret_thunk_extern
  ATTR_KIND_SKIP_PROFILE = 85,                      ///< skipprofile
  ATTR_KIND_MEMORY = 86,                            ///< memory
  ATTR_KIND_NOFPCLASS = 87,                         ///< nofpclass
  ATTR_KIND_OPTIMIZE_FOR_DEBUGGING = 88,            ///< optdebug
  ATTR_KIND_WRITABLE = 89,                          ///< writable
  ATTR_KIND_CORO_ONLY_DESTROY_WHEN_COMPLETE = 90,   ///< coro_only_destroy_when_complete
  ATTR_KIND_DEAD_ON_UNWIND = 91,                    ///< dead_on_unwind
  ATTR_KIND_RANGE = 92,                             ///< range
  ATTR_KIND_SANITIZE_NUMERICAL_STABILITY = 93,      ///< sanitize_numerical_stability
  ATTR_KIND_INITIALIZES = 94,                       ///< initializes
  ATTR_KIND_HYBRID_PATCHABLE = 95,                  ///< hybrid_patchable
  ATTR_KIND_SANITIZE_REALTIME = 96,                 ///< sanitize_realtime
  ATTR_KIND_SANITIZE_REALTIME_BLOCKING = 97,        ///< sanitize_realtime_blocking
  ATTR_KIND_CORO_ELIDE_SAFE = 98,                   ///< coro_elide_safe
  ATTR_KIND_NO_EXT = 99,                            ///< noext
  ATTR_KIND_NO_DIVERGENCE_SOURCE = 100,             ///< nodivergencesource
  ATTR_KIND_SANITIZE_TYPE = 101,                    ///< sanitize_type
  ATTR_KIND_CAPTURES = 102,                         ///< captures
  ATTR_KIND_DEAD_ON_RETURN = 103,                   ///< dead_on_return
  ATTR_KIND_SANITIZE_ALLOC_TOKEN = 104,             ///< sanitize_alloc_token
  ATTR_KIND_NO_CREATE_UNDEF_OR_POISON = 105,        ///< nocreateundeforpoison
  ATTR_KIND_DENORMAL_FPENV = 106,                   ///< denormal_fp_math
  ATTR_KIND_NOOUTLINE = 107,                        ///< nooutline
  ATTR_KIND_FLATTEN = 108,                          ///< flatten
  ATTR_KIND_NOIPA = 109,                            ///< noipa
  ATTR_KIND_NOFREEOBJ = 110,                        ///< nofreeobj
};

/// COMDAT selection kind encodings used in MODULE_CODE_COMDAT records.
enum ComdatSelectionKindCodes {
  COMDAT_SELECTION_KIND_ANY = 1,           ///< Any selection kind.
  COMDAT_SELECTION_KIND_EXACT_MATCH = 2,   ///< Exact match selection kind.
  COMDAT_SELECTION_KIND_LARGEST = 3,       ///< Largest selection kind.
  COMDAT_SELECTION_KIND_NO_DUPLICATES = 4, ///< No duplicates selection kind.
  COMDAT_SELECTION_KIND_SAME_SIZE = 5,     ///< Same size selection kind.
};

/// String table block record codes.
enum StrtabCodes {
  STRTAB_BLOB = 1, ///< String table blob payload.
};

/// Symbol table block record codes.
enum SymtabCodes {
  SYMTAB_BLOB = 1, ///< Symbol table blob payload.
};

} // End bitc namespace
} // End llvm namespace

#endif
