//===-- llvm/MC/MCObjectFileInfo.h - Object File Info -----------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file describes common object file formats.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_MC_MCOBJECTFILEINFO_H
#define LLVM_MC_MCOBJECTFILEINFO_H

#include "llvm/BinaryFormat/SFrame.h"
#include "llvm/BinaryFormat/Swift.h"
#include "llvm/MC/MCSection.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/VersionTuple.h"
#include "llvm/TargetParser/Triple.h"

#include <array>
#include <optional>

namespace llvm {
class MCContext;
class MCSection;

/// Holds section handles and related object-file metadata for MC emission.
class LLVM_ABI MCObjectFileInfo {
protected:
  /// True if the target object file supports emitting a compact unwind section
  /// without an associated EH frame section.
  bool SupportsCompactUnwindWithoutEHFrame = false;

  /// OmitDwarfIfHaveCompactUnwind - True if the target object file
  /// supports having some functions with compact unwind and other with
  /// dwarf unwind.
  bool OmitDwarfIfHaveCompactUnwind = false;

  /// Encoding used for FDE CFI begin labels in `.eh_frame`.
  ///
  /// Controls the encoding of the begin label in the .eh_frame section. Unlike
  /// the LSDA encoding, personality encoding, and type encodings, this is
  /// something that the assembler just "knows" about its target.
  unsigned FDECFIEncoding = 0;

  /// Compact unwind encoding indicating that we should emit only an EH frame.
  unsigned CompactUnwindDwarfEHFrameOnly = 0;

  /// SFrame ABI architecture byte.
  std::optional<sframe::ABI> SFrameABIArch = {};

  /// Section directive for standard text.
  MCSection *TextSection = nullptr;

  /// Section directive for standard data.
  MCSection *DataSection = nullptr;

  /// Section that is default initialized to zero.
  MCSection *BSSSection = nullptr;

  /// Readonly section for arbitrary initialized data.
  ///
  /// Targets are not required to have a readonly section. If they don't,
  /// various bits of code will fall back to using the data section for
  /// constants.
  MCSection *ReadOnlySection = nullptr;

  /// If exception handling is supported by the target, this is the section the
  /// Language Specific Data Area information is emitted to.
  MCSection *LSDASection = nullptr;

  /// Section containing call graph metadata.
  MCSection *CallGraphSection = nullptr;

  /// If exception handling is supported by the target and the target can
  /// support a compact representation of the CIE and FDE, this is the section
  /// to emit them into.
  MCSection *CompactUnwindSection = nullptr;

  /// If import call optimization is supported by the target, this is the
  /// section to emit import call data to.
  MCSection *ImportCallSection = nullptr;

  // Dwarf sections for debug info.  If a target supports debug info, these must
  // be set.
  /// DWARF abbreviation section (`.debug_abbrev`).
  MCSection *DwarfAbbrevSection = nullptr;
  /// DWARF compilation-unit info section (`.debug_info`).
  MCSection *DwarfInfoSection = nullptr;
  /// DWARF line-number program section (`.debug_line`).
  MCSection *DwarfLineSection = nullptr;
  /// DWARF line-string section (`.debug_line_str`).
  MCSection *DwarfLineStrSection = nullptr;
  /// DWARF call-frame information section (`.debug_frame`).
  MCSection *DwarfFrameSection = nullptr;
  /// DWARF public types section (`.debug_pubtypes`).
  MCSection *DwarfPubTypesSection = nullptr;
  /// Legacy DWARF inline debug info section.
  const MCSection *DwarfDebugInlineSection = nullptr;
  /// DWARF string section (`.debug_str`).
  MCSection *DwarfStrSection = nullptr;
  /// DWARF location list section (`.debug_loc`).
  MCSection *DwarfLocSection = nullptr;
  /// DWARF address-range section (`.debug_aranges`).
  MCSection *DwarfARangesSection = nullptr;
  /// DWARF range list section (`.debug_ranges`).
  MCSection *DwarfRangesSection = nullptr;
  /// DWARF macinfo section (`.debug_macinfo`).
  MCSection *DwarfMacinfoSection = nullptr;
  /// DWARF macro section (`.debug_macro`).
  MCSection *DwarfMacroSection = nullptr;
  // The pubnames section is no longer generated by default.  The generation
  // can be enabled by a compiler flag.
  /// DWARF public names section (`.debug_pubnames`).
  MCSection *DwarfPubNamesSection = nullptr;

  /// DWARF v5 accelerator table section (`.debug_names`).
  ///
  /// Accelerator table sections. DwarfDebugNamesSection is the DWARF v5
  /// accelerator table, while DwarfAccelNamesSection, DwarfAccelObjCSection,
  /// DwarfAccelNamespaceSection, DwarfAccelTypesSection are pre-DWARF v5
  /// extensions.
  MCSection *DwarfDebugNamesSection = nullptr;
  /// Pre-DWARF v5 Apple-style names accelerator table section.
  MCSection *DwarfAccelNamesSection = nullptr;
  /// Pre-DWARF v5 Apple-style Objective-C accelerator table section.
  MCSection *DwarfAccelObjCSection = nullptr;
  /// Pre-DWARF v5 Apple-style namespace accelerator table section.
  MCSection *DwarfAccelNamespaceSection = nullptr;
  /// Pre-DWARF v5 Apple-style types accelerator table section.
  MCSection *DwarfAccelTypesSection = nullptr;

  // These are used for the Fission separate debug information files.
  /// Fission (DWO) DWARF info section (`.debug_info.dwo`).
  MCSection *DwarfInfoDWOSection = nullptr;
  /// Fission (DWO) DWARF types section (`.debug_types.dwo`).
  MCSection *DwarfTypesDWOSection = nullptr;
  /// Fission (DWO) DWARF abbreviation section (`.debug_abbrev.dwo`).
  MCSection *DwarfAbbrevDWOSection = nullptr;
  /// Fission (DWO) DWARF string section (`.debug_str.dwo`).
  MCSection *DwarfStrDWOSection = nullptr;
  /// Fission (DWO) DWARF line section (`.debug_line.dwo`).
  MCSection *DwarfLineDWOSection = nullptr;
  /// Fission (DWO) DWARF location list section (`.debug_loc.dwo`).
  MCSection *DwarfLocDWOSection = nullptr;
  /// Fission (DWO) DWARF string-offset section (`.debug_str_offsets.dwo`).
  MCSection *DwarfStrOffDWOSection = nullptr;
  /// Fission (DWO) DWARF macinfo section (`.debug_macinfo.dwo`).
  MCSection *DwarfMacinfoDWOSection = nullptr;
  /// Fission (DWO) DWARF macro section (`.debug_macro.dwo`).
  MCSection *DwarfMacroDWOSection = nullptr;

  /// The DWARF v5 string offset and address table sections.
  MCSection *DwarfStrOffSection = nullptr;
  /// DWARF v5 address table section (`.debug_addr`).
  MCSection *DwarfAddrSection = nullptr;
  /// The DWARF v5 range list section.
  MCSection *DwarfRnglistsSection = nullptr;
  /// The DWARF v5 locations list section.
  MCSection *DwarfLoclistsSection = nullptr;

  /// The DWARF v5 range and location list sections for fission.
  MCSection *DwarfRnglistsDWOSection = nullptr;
  /// Fission (DWO) DWARF v5 location list section (`.debug_loclists.dwo`).
  MCSection *DwarfLoclistsDWOSection = nullptr;

  // These are for Fission DWP files.
  /// DWARF package CU index section (`.debug_cu_index`).
  MCSection *DwarfCUIndexSection = nullptr;
  /// DWARF package TU index section (`.debug_tu_index`).
  MCSection *DwarfTUIndexSection = nullptr;

  /// Section for newer gnu pubnames.
  MCSection *DwarfGnuPubNamesSection = nullptr;
  /// Section for newer gnu pubtypes.
  MCSection *DwarfGnuPubTypesSection = nullptr;

  // Section for Swift AST
  /// Section holding serialized Swift AST debug data.
  MCSection *DwarfSwiftASTSection = nullptr;

  /// COFF CodeView debug symbols section.
  MCSection *COFFDebugSymbolsSection = nullptr;
  /// COFF CodeView debug types section.
  MCSection *COFFDebugTypesSection = nullptr;
  /// COFF global type hashes section.
  MCSection *COFFGlobalTypeHashesSection = nullptr;

  /// Extra TLS Variable Data section.
  ///
  /// If the target needs to put additional information for a TLS variable,
  /// it'll go here.
  MCSection *TLSExtraDataSection = nullptr;

  /// Section directive for Thread Local data. ELF, MachO, COFF, and Wasm.
  MCSection *TLSDataSection = nullptr; // Defaults to ".tdata".

  /// Section directive for Thread Local uninitialized data.
  ///
  /// Null if this target doesn't support a BSS section. ELF and MachO only.
  MCSection *TLSBSSSection = nullptr; // Defaults to ".tbss".

  /// StackMap section.
  MCSection *StackMapSection = nullptr;

  /// FaultMap section.
  MCSection *FaultMapSection = nullptr;

  /// Remarks section.
  MCSection *RemarksSection = nullptr;

  /// EH frame section.
  ///
  /// It is initialized on demand so it can be overwritten (with uniquing).
  MCSection *EHFrameSection = nullptr;

  /// SFrame section.
  MCSection *SFrameSection = nullptr;

  /// Section containing metadata on function stack sizes.
  MCSection *StackSizesSection = nullptr;

  /// Section for pseudo probe information used by AutoFDO
  MCSection *PseudoProbeSection = nullptr;
  /// Section describing AutoFDO pseudo-probe function descriptors.
  MCSection *PseudoProbeDescSection = nullptr;

  // Section for metadata of llvm statistics.
  /// Section holding LLVM statistics metadata.
  MCSection *LLVMStatsSection = nullptr;

  // ELF specific sections.
  /// ELF section for read-only data that needs dynamic relocations.
  MCSection *DataRelROSection = nullptr;
  /// ELF mergeable 4-byte constant section.
  MCSection *MergeableConst4Section = nullptr;
  /// ELF mergeable 8-byte constant section.
  MCSection *MergeableConst8Section = nullptr;
  /// ELF mergeable 16-byte constant section.
  MCSection *MergeableConst16Section = nullptr;
  /// ELF mergeable 32-byte constant section.
  MCSection *MergeableConst32Section = nullptr;

  // MachO specific sections.

  /// Section for thread local structure information.
  ///
  /// Contains the source code name of the variable, visibility and a pointer to
  /// the initial value (.tdata or .tbss).
  MCSection *TLSTLVSection = nullptr; // Defaults to ".tlv".

  /// Section for thread local data initialization functions.
 // Defaults to ".thread_init_func".
  const MCSection *TLSThreadInitSection = nullptr;

  /// Mach-O C-string literal section.
  MCSection *CStringSection = nullptr;
  /// Mach-O UTF-16 string literal section.
  MCSection *UStringSection = nullptr;
  /// Mach-O coalesced text section.
  MCSection *TextCoalSection = nullptr;
  /// Mach-O coalesced constant text section.
  MCSection *ConstTextCoalSection = nullptr;
  /// Mach-O constant data section.
  MCSection *ConstDataSection = nullptr;
  /// Mach-O coalesced data section.
  MCSection *DataCoalSection = nullptr;
  /// Mach-O coalesced constant data section.
  MCSection *ConstDataCoalSection = nullptr;
  /// Mach-O common data section.
  MCSection *DataCommonSection = nullptr;
  /// Mach-O BSS data section.
  MCSection *DataBSSSection = nullptr;
  /// Mach-O 4-byte constant section.
  MCSection *FourByteConstantSection = nullptr;
  /// Mach-O 8-byte constant section.
  MCSection *EightByteConstantSection = nullptr;
  /// Mach-O 16-byte constant section.
  MCSection *SixteenByteConstantSection = nullptr;
  /// Mach-O lazy symbol pointer section.
  MCSection *LazySymbolPointerSection = nullptr;
  /// Mach-O non-lazy symbol pointer section.
  MCSection *NonLazySymbolPointerSection = nullptr;
  /// Mach-O thread-local pointer section.
  MCSection *ThreadLocalPointerSection = nullptr;
  /// Address-significance table section.
  MCSection *AddrSigSection = nullptr;

  // COFF specific sections.
  /// COFF linker directives section (`.drectve`).
  MCSection *DrectveSection = nullptr;
  /// COFF exception procedure data section (`.pdata`).
  MCSection *PDataSection = nullptr;
  /// COFF exception unwind data section (`.xdata`).
  MCSection *XDataSection = nullptr;
  /// COFF safe exception handlers data section (`.sxdata`).
  MCSection *SXDataSection = nullptr;
  /// COFF guard EH continuation table section.
  MCSection *GEHContSection = nullptr;
  /// COFF guard function ID table section.
  MCSection *GFIDsSection = nullptr;
  /// COFF guard address-taken IAT entries section.
  MCSection *GIATsSection = nullptr;
  /// COFF guard longjmp table section.
  MCSection *GLJMPSection = nullptr;

  // GOFF specific sections.
  /// GOFF PPA2 list section.
  MCSection *PPA2ListSection = nullptr;
  /// GOFF associated data area (ADA) section.
  MCSection *ADASection = nullptr;
  /// GOFF IDRL section.
  MCSection *IDRLSection = nullptr;

  // XCOFF specific sections
  /// XCOFF TOC base section.
  MCSection *TOCBaseSection = nullptr;
  /// XCOFF 8-byte read-only section.
  MCSection *ReadOnly8Section = nullptr;
  /// XCOFF 16-byte read-only section.
  MCSection *ReadOnly16Section = nullptr;

  // Swift5 Reflection Data Sections
  /// Swift 5 reflection metadata sections, indexed by section kind.
  std::array<MCSection *, binaryformat::Swift5ReflectionSectionKind::last>
      Swift5ReflectionSections = {};

public:
  /// Initialize object-file section info for the given context and code model.
  /// @param MCCtx MC context used to create and own sections.
  /// @param PIC True when generating position-independent code.
  /// @param LargeCodeModel True when using the large code model.
  void initMCObjectFileInfo(MCContext &MCCtx, bool PIC,
                            bool LargeCodeModel = false);
  /// Destroy this object-file info instance.
  virtual ~MCObjectFileInfo();
  /// Return the MC context associated with this object-file info.
  /// @return The MC context associated with this object-file info.
  MCContext &getContext() const { return *Ctx; }

  /// True if compact unwind can be emitted without an EH frame section.
  /// @return True if compact unwind can be emitted without an EH frame
  /// section.
  bool getSupportsCompactUnwindWithoutEHFrame() const {
    return SupportsCompactUnwindWithoutEHFrame;
  }
  /// True if DWARF unwind may be omitted when compact unwind is available.
  /// @return True if DWARF unwind may be omitted when compact unwind is
  /// available.
  bool getOmitDwarfIfHaveCompactUnwind() const {
    return OmitDwarfIfHaveCompactUnwind;
  }

  /// Return the FDE CFI encoding used for `.eh_frame` begin labels.
  /// @return The FDE CFI encoding used for `.eh_frame` begin labels.
  unsigned getFDEEncoding() const { return FDECFIEncoding; }

  /// Return the compact-unwind encoding that means emit only an EH frame.
  /// @return The compact-unwind encoding that means emit only an EH frame.
  unsigned getCompactUnwindDwarfEHFrameOnly() const {
    return CompactUnwindDwarfEHFrameOnly;
  }

  /// Return the optional SFrame ABI architecture identifier.
  /// @return The optional SFrame ABI architecture identifier.
  std::optional<sframe::ABI> getSFrameABIArch() const { return SFrameABIArch; }
  /// Return the preferred alignment in bytes for the text section.
  /// @return The preferred alignment in bytes for the text section.
  virtual unsigned getTextSectionAlignment() const { return 4; }
  /// Return the standard text section.
  /// @return The standard text section.
  MCSection *getTextSection() const { return TextSection; }
  /// Return the standard data section.
  /// @return The standard data section.
  MCSection *getDataSection() const { return DataSection; }
  /// Return the BSS section.
  /// @return The BSS section.
  MCSection *getBSSSection() const { return BSSSection; }
  /// Return the read-only data section.
  /// @return The read-only data section.
  MCSection *getReadOnlySection() const { return ReadOnlySection; }
  /// Return the language-specific data area (LSDA) section.
  /// @return The language-specific data area (LSDA) section.
  MCSection *getLSDASection() const { return LSDASection; }
  /// Return the import-call optimization data section.
  /// @return The import-call optimization data section.
  MCSection *getImportCallSection() const { return ImportCallSection; }
  /// Return the compact unwind section.
  /// @return The compact unwind section.
  MCSection *getCompactUnwindSection() const { return CompactUnwindSection; }
  /// Return the DWARF abbreviation section.
  /// @return The DWARF abbreviation section.
  MCSection *getDwarfAbbrevSection() const { return DwarfAbbrevSection; }
  /// Return the DWARF info section.
  /// @return The DWARF info section.
  MCSection *getDwarfInfoSection() const { return DwarfInfoSection; }
  /// Return the DWARF info COMDAT section for the given hash.
  /// @param Hash COMDAT key identifying the unique info section.
  /// @return The DWARF info COMDAT section for the given hash.
  MCSection *getDwarfInfoSection(uint64_t Hash) const {
    return getDwarfComdatSection(".debug_info", Hash);
  }
  /// Return the DWARF line section.
  /// @return The DWARF line section.
  MCSection *getDwarfLineSection() const { return DwarfLineSection; }
  /// Return the DWARF line-string section.
  /// @return The DWARF line-string section.
  MCSection *getDwarfLineStrSection() const { return DwarfLineStrSection; }
  /// Return the DWARF frame section.
  /// @return The DWARF frame section.
  MCSection *getDwarfFrameSection() const { return DwarfFrameSection; }
  /// Return the DWARF public names section.
  /// @return The DWARF public names section.
  MCSection *getDwarfPubNamesSection() const { return DwarfPubNamesSection; }
  /// Return the DWARF public types section.
  /// @return The DWARF public types section.
  MCSection *getDwarfPubTypesSection() const { return DwarfPubTypesSection; }
  /// Return the GNU-style DWARF public names section.
  /// @return The GNU-style DWARF public names section.
  MCSection *getDwarfGnuPubNamesSection() const {
    return DwarfGnuPubNamesSection;
  }
  /// Return the GNU-style DWARF public types section.
  /// @return The GNU-style DWARF public types section.
  MCSection *getDwarfGnuPubTypesSection() const {
    return DwarfGnuPubTypesSection;
  }
  /// Return the legacy DWARF inline debug info section.
  /// @return The legacy DWARF inline debug info section.
  const MCSection *getDwarfDebugInlineSection() const {
    return DwarfDebugInlineSection;
  }
  /// Return the DWARF string section.
  /// @return The DWARF string section.
  MCSection *getDwarfStrSection() const { return DwarfStrSection; }
  /// Return the DWARF location list section.
  /// @return The DWARF location list section.
  MCSection *getDwarfLocSection() const { return DwarfLocSection; }
  /// Return the DWARF address-range section.
  /// @return The DWARF address-range section.
  MCSection *getDwarfARangesSection() const { return DwarfARangesSection; }
  /// Return the DWARF ranges section.
  /// @return The DWARF ranges section.
  MCSection *getDwarfRangesSection() const { return DwarfRangesSection; }
  /// Return the DWARF v5 range list section.
  /// @return The DWARF v5 range list section.
  MCSection *getDwarfRnglistsSection() const { return DwarfRnglistsSection; }
  /// Return the DWARF v5 location list section.
  /// @return The DWARF v5 location list section.
  MCSection *getDwarfLoclistsSection() const { return DwarfLoclistsSection; }
  /// Return the DWARF macinfo section.
  /// @return The DWARF macinfo section.
  MCSection *getDwarfMacinfoSection() const { return DwarfMacinfoSection; }
  /// Return the DWARF macro section.
  /// @return The DWARF macro section.
  MCSection *getDwarfMacroSection() const { return DwarfMacroSection; }

  /// Return the DWARF v5 `.debug_names` accelerator table section.
  /// @return The DWARF v5 `.debug_names` accelerator table section.
  MCSection *getDwarfDebugNamesSection() const {
    return DwarfDebugNamesSection;
  }
  /// Return the Apple-style names accelerator table section.
  /// @return The Apple-style names accelerator table section.
  MCSection *getDwarfAccelNamesSection() const {
    return DwarfAccelNamesSection;
  }
  /// Return the Apple-style Objective-C accelerator table section.
  /// @return The Apple-style Objective-C accelerator table section.
  MCSection *getDwarfAccelObjCSection() const { return DwarfAccelObjCSection; }
  /// Return the Apple-style namespace accelerator table section.
  /// @return The Apple-style namespace accelerator table section.
  MCSection *getDwarfAccelNamespaceSection() const {
    return DwarfAccelNamespaceSection;
  }
  /// Return the Apple-style types accelerator table section.
  /// @return The Apple-style types accelerator table section.
  MCSection *getDwarfAccelTypesSection() const {
    return DwarfAccelTypesSection;
  }
  /// Return the fission DWARF info section.
  /// @return The fission DWARF info section.
  MCSection *getDwarfInfoDWOSection() const { return DwarfInfoDWOSection; }
  /// Return the DWARF types COMDAT section for the given hash.
  /// @param Hash COMDAT key identifying the unique types section.
  /// @return The DWARF types COMDAT section for the given hash.
  MCSection *getDwarfTypesSection(uint64_t Hash) const {
    return getDwarfComdatSection(".debug_types", Hash);
  }
  /// Return the fission DWARF types section.
  /// @return The fission DWARF types section.
  MCSection *getDwarfTypesDWOSection() const { return DwarfTypesDWOSection; }
  /// Return the fission DWARF abbreviation section.
  /// @return The fission DWARF abbreviation section.
  MCSection *getDwarfAbbrevDWOSection() const { return DwarfAbbrevDWOSection; }
  /// Return the fission DWARF string section.
  /// @return The fission DWARF string section.
  MCSection *getDwarfStrDWOSection() const { return DwarfStrDWOSection; }
  /// Return the fission DWARF line section.
  /// @return The fission DWARF line section.
  MCSection *getDwarfLineDWOSection() const { return DwarfLineDWOSection; }
  /// Return the fission DWARF location list section.
  /// @return The fission DWARF location list section.
  MCSection *getDwarfLocDWOSection() const { return DwarfLocDWOSection; }
  /// Return the fission DWARF string-offset section.
  /// @return The fission DWARF string-offset section.
  MCSection *getDwarfStrOffDWOSection() const { return DwarfStrOffDWOSection; }
  /// Return the DWARF v5 string-offset section.
  /// @return The DWARF v5 string-offset section.
  MCSection *getDwarfStrOffSection() const { return DwarfStrOffSection; }
  /// Return the DWARF v5 address table section.
  /// @return The DWARF v5 address table section.
  MCSection *getDwarfAddrSection() const { return DwarfAddrSection; }
  /// Return the fission DWARF v5 range list section.
  /// @return The fission DWARF v5 range list section.
  MCSection *getDwarfRnglistsDWOSection() const {
    return DwarfRnglistsDWOSection;
  }
  /// Return the fission DWARF v5 location list section.
  /// @return The fission DWARF v5 location list section.
  MCSection *getDwarfLoclistsDWOSection() const {
    return DwarfLoclistsDWOSection;
  }
  /// Return the fission DWARF macro section.
  /// @return The fission DWARF macro section.
  MCSection *getDwarfMacroDWOSection() const { return DwarfMacroDWOSection; }
  /// Return the fission DWARF macinfo section.
  /// @return The fission DWARF macinfo section.
  MCSection *getDwarfMacinfoDWOSection() const {
    return DwarfMacinfoDWOSection;
  }
  /// Return the DWARF package CU index section.
  /// @return The DWARF package CU index section.
  MCSection *getDwarfCUIndexSection() const { return DwarfCUIndexSection; }
  /// Return the DWARF package TU index section.
  /// @return The DWARF package TU index section.
  MCSection *getDwarfTUIndexSection() const { return DwarfTUIndexSection; }
  /// Return the Swift AST debug section.
  /// @return The Swift AST debug section.
  MCSection *getDwarfSwiftASTSection() const { return DwarfSwiftASTSection; }

  /// Return the COFF CodeView debug symbols section.
  /// @return The COFF CodeView debug symbols section.
  MCSection *getCOFFDebugSymbolsSection() const {
    return COFFDebugSymbolsSection;
  }
  /// Return the COFF CodeView debug types section.
  /// @return The COFF CodeView debug types section.
  MCSection *getCOFFDebugTypesSection() const {
    return COFFDebugTypesSection;
  }
  /// Return the COFF global type hashes section.
  /// @return The COFF global type hashes section.
  MCSection *getCOFFGlobalTypeHashesSection() const {
    return COFFGlobalTypeHashesSection;
  }

  /// Return the extra TLS variable data section.
  /// @return The extra TLS variable data section.
  MCSection *getTLSExtraDataSection() const { return TLSExtraDataSection; }
  /// Return the thread-local initialized data section.
  /// @return The thread-local initialized data section.
  const MCSection *getTLSDataSection() const { return TLSDataSection; }
  /// Return the thread-local BSS section.
  /// @return The thread-local BSS section.
  MCSection *getTLSBSSSection() const { return TLSBSSSection; }

  /// Return the stack map section.
  /// @return The stack map section.
  MCSection *getStackMapSection() const { return StackMapSection; }
  /// Return the fault map section.
  /// @return The fault map section.
  MCSection *getFaultMapSection() const { return FaultMapSection; }
  /// Return the remarks section.
  /// @return The remarks section.
  MCSection *getRemarksSection() const { return RemarksSection; }

  /// Return the call-graph metadata section for \p TextSec.
  /// @param TextSec Text section whose call-graph metadata is requested.
  /// @return The call-graph metadata section for \p TextSec.
  MCSection *getCallGraphSection(const MCSection &TextSec) const;

  /// Return the stack-sizes metadata section for \p TextSec.
  /// @param TextSec Text section whose stack-size metadata is requested.
  /// @return The stack-sizes metadata section for \p TextSec.
  MCSection *getStackSizesSection(const MCSection &TextSec) const;

  /// Return the basic-block address map section for \p TextSec.
  /// @param TextSec Text section whose BB address map is requested.
  /// @return The basic-block address map section for \p TextSec.
  MCSection *getBBAddrMapSection(const MCSection &TextSec) const;

  /// Return the KCFI trap section for \p TextSec.
  /// @param TextSec Text section whose KCFI trap metadata is requested.
  /// @return The KCFI trap section for \p TextSec.
  MCSection *getKCFITrapSection(const MCSection &TextSec) const;

  /// Return the AutoFDO pseudo-probe section for \p TextSec.
  /// @param TextSec Text section whose pseudo-probe data is requested.
  /// @return The AutoFDO pseudo-probe section for \p TextSec.
  MCSection *getPseudoProbeSection(const MCSection &TextSec) const;

  /// Return the AutoFDO pseudo-probe descriptor section for a function.
  /// @param FuncName Name of the function being described.
  /// @param FuncHash Hash identifying the function version.
  /// @return The AutoFDO pseudo-probe descriptor section for the function.
  MCSection *getPseudoProbeDescSection(StringRef FuncName,
                                       uint64_t FuncHash) const;

  /// Return the LLVM statistics metadata section.
  /// @return The LLVM statistics metadata section.
  MCSection *getLLVMStatsSection() const;

  /// Return or create a PC-relative metadata section named \p Name.
  /// @param Name Section name to look up or create.
  /// @param TextSec Optional associated text section.
  /// @return The PC-relative metadata section named \p Name.
  MCSection *getPCSection(StringRef Name, const MCSection *TextSec) const;

  // MachO specific sections.
  /// Return the Mach-O thread-local variable structure section.
  /// @return The Mach-O thread-local variable structure section.
  const MCSection *getTLSTLVSection() const { return TLSTLVSection; }
  /// Return the Mach-O TLS thread-init function section.
  /// @return The Mach-O TLS thread-init function section.
  const MCSection *getTLSThreadInitSection() const {
    return TLSThreadInitSection;
  }
  /// Return the Mach-O C-string literal section.
  /// @return The Mach-O C-string literal section.
  const MCSection *getCStringSection() const { return CStringSection; }
  /// Return the Mach-O UTF-16 string literal section.
  /// @return The Mach-O UTF-16 string literal section.
  const MCSection *getUStringSection() const { return UStringSection; }
  /// Return the Mach-O coalesced text section.
  /// @return The Mach-O coalesced text section.
  MCSection *getTextCoalSection() const { return TextCoalSection; }
  /// Return the Mach-O coalesced constant text section.
  /// @return The Mach-O coalesced constant text section.
  const MCSection *getConstTextCoalSection() const {
    return ConstTextCoalSection;
  }
  /// Return the Mach-O constant data section.
  /// @return The Mach-O constant data section.
  const MCSection *getConstDataSection() const { return ConstDataSection; }
  /// Return the Mach-O coalesced data section.
  /// @return The Mach-O coalesced data section.
  const MCSection *getDataCoalSection() const { return DataCoalSection; }
  /// Return the Mach-O coalesced constant data section.
  /// @return The Mach-O coalesced constant data section.
  const MCSection *getConstDataCoalSection() const {
    return ConstDataCoalSection;
  }
  /// Return the Mach-O common data section.
  /// @return The Mach-O common data section.
  const MCSection *getDataCommonSection() const { return DataCommonSection; }
  /// Return the Mach-O BSS data section.
  /// @return The Mach-O BSS data section.
  MCSection *getDataBSSSection() const { return DataBSSSection; }
  /// Return the Mach-O 4-byte constant section.
  /// @return The Mach-O 4-byte constant section.
  const MCSection *getFourByteConstantSection() const {
    return FourByteConstantSection;
  }
  /// Return the Mach-O 8-byte constant section.
  /// @return The Mach-O 8-byte constant section.
  const MCSection *getEightByteConstantSection() const {
    return EightByteConstantSection;
  }
  /// Return the Mach-O 16-byte constant section.
  /// @return The Mach-O 16-byte constant section.
  const MCSection *getSixteenByteConstantSection() const {
    return SixteenByteConstantSection;
  }
  /// Return the Mach-O lazy symbol pointer section.
  /// @return The Mach-O lazy symbol pointer section.
  MCSection *getLazySymbolPointerSection() const {
    return LazySymbolPointerSection;
  }
  /// Return the Mach-O non-lazy symbol pointer section.
  /// @return The Mach-O non-lazy symbol pointer section.
  MCSection *getNonLazySymbolPointerSection() const {
    return NonLazySymbolPointerSection;
  }
  /// Return the Mach-O thread-local pointer section.
  /// @return The Mach-O thread-local pointer section.
  MCSection *getThreadLocalPointerSection() const {
    return ThreadLocalPointerSection;
  }
  /// Return the address-significance table section.
  /// @return The address-significance table section.
  MCSection *getAddrSigSection() const { return AddrSigSection; }

  // COFF specific sections.
  /// Return the COFF linker directives section.
  /// @return The COFF linker directives section.
  MCSection *getDrectveSection() const { return DrectveSection; }
  /// Return the COFF procedure data section.
  /// @return The COFF procedure data section.
  MCSection *getPDataSection() const { return PDataSection; }
  /// Return the COFF unwind data section.
  /// @return The COFF unwind data section.
  MCSection *getXDataSection() const { return XDataSection; }
  /// Return the COFF safe exception handlers data section.
  /// @return The COFF safe exception handlers data section.
  MCSection *getSXDataSection() const { return SXDataSection; }
  /// Return the COFF guard EH continuation table section.
  /// @return The COFF guard EH continuation table section.
  MCSection *getGEHContSection() const { return GEHContSection; }
  /// Return the COFF guard function ID table section.
  /// @return The COFF guard function ID table section.
  MCSection *getGFIDsSection() const { return GFIDsSection; }
  /// Return the COFF guard address-taken IAT entries section.
  /// @return The COFF guard address-taken IAT entries section.
  MCSection *getGIATsSection() const { return GIATsSection; }
  /// Return the COFF guard longjmp table section.
  /// @return The COFF guard longjmp table section.
  MCSection *getGLJMPSection() const { return GLJMPSection; }

  // GOFF specific sections.
  /// Return the GOFF PPA2 list section.
  /// @return The GOFF PPA2 list section.
  MCSection *getPPA2ListSection() const { return PPA2ListSection; }
  /// Return the GOFF associated data area section.
  /// @return The GOFF associated data area section.
  MCSection *getADASection() const { return ADASection; }
  /// Return the GOFF IDRL section.
  /// @return The GOFF IDRL section.
  MCSection *getIDRLSection() const { return IDRLSection; }

  // XCOFF specific sections
  /// Return the XCOFF TOC base section.
  /// @return The XCOFF TOC base section.
  MCSection *getTOCBaseSection() const { return TOCBaseSection; }

  /// Return the EH frame section.
  /// @return The EH frame section.
  MCSection *getEHFrameSection() const { return EHFrameSection; }
  /// Return the SFrame section.
  /// @return The SFrame section.
  MCSection *getSFrameSection() const { return SFrameSection; }

  /// True if the object file is being built for position-independent code.
  /// @return True if the object file is being built for position-independent
  /// code.
  bool isPositionIndependent() const { return PositionIndependent; }

  // Swift5 Reflection Data Sections
  /// Return the Swift 5 reflection section for \p ReflSectionKind.
  /// @param ReflSectionKind Kind of Swift 5 reflection section to retrieve.
  /// @return The Swift 5 reflection section, or null for unknown kinds.
  MCSection *getSwift5ReflectionSection(
      llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind) {
    return ReflSectionKind !=
                   llvm::binaryformat::Swift5ReflectionSectionKind::unknown
               ? Swift5ReflectionSections[ReflSectionKind]
               : nullptr;
  }

private:
  bool PositionIndependent = false;
  MCContext *Ctx = nullptr;

  void initMachOMCObjectFileInfo(const Triple &T);
  void initELFMCObjectFileInfo(const Triple &T, bool Large);
  void initGOFFMCObjectFileInfo(const Triple &T);
  void initCOFFMCObjectFileInfo(const Triple &T);
  void initSPIRVMCObjectFileInfo(const Triple &T);
  void initWasmMCObjectFileInfo(const Triple &T);
  void initXCOFFMCObjectFileInfo(const Triple &T);
  void initDXContainerObjectFileInfo(const Triple &T);
  MCSection *getDwarfComdatSection(const char *Name, uint64_t Hash) const;
};

} // end namespace llvm

#endif
