//===-- llvm/Support/DOTGraphTraits.h - Customize .dot output ---*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file defines a template class that can be used to customize dot output
// graphs generated by the GraphWriter.h file.  The default implementation of
// this file will produce a simple, but not very polished graph.  By
// specializing this template, lots of customization opportunities are possible.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_SUPPORT_DOTGRAPHTRAITS_H
#define LLVM_SUPPORT_DOTGRAPHTRAITS_H

#include <string>

namespace llvm {

/// Default implementations of all DOTGraphTraits customization hooks.
///
/// If a specialization does not need to override all methods here it should
/// inherit so that it can get the default implementations.
struct DefaultDOTGraphTraits {
private:
  bool IsSimple;

protected:
  /// Return true if this traits instance was constructed for simple names.
  ///
  /// \return True when short node names were requested at construction.
  bool isSimple() {
    return IsSimple;
  }

public:
  /// Construct traits that optionally request short node names.
  ///
  /// \param simple If true, prefer short labels over detailed ones.
  explicit DefaultDOTGraphTraits(bool simple=false) : IsSimple (simple) {}

  /// Return the label for the graph as a whole.
  ///
  /// Printed at the top of the graph.
  ///
  /// \param G Graph whose display name is requested.
  /// \return Graph display name, or an empty string when none is provided.
  template<typename GraphType>
  static std::string getGraphName(const GraphType &G) { return ""; }

  /// Return custom properties for the top-level DOT graph structure.
  ///
  /// \param G Graph whose DOT properties are requested.
  /// \return DOT property string for the graph, or empty when none are set.
  template<typename GraphType>
  static std::string getGraphProperties(const GraphType &G) {
    return "";
  }

  /// renderGraphFromBottomUp - If this function returns true, the graph is
  /// emitted bottom-up instead of top-down.  This requires graphviz 2.0 to work
  /// though.
  ///
  /// \return True when the graph should be emitted bottom-up.
  static bool renderGraphFromBottomUp() {
    return false;
  }

  /// Return true if the given node should be omitted from the graph.
  ///
  /// \param Node Node to test for visibility.
  /// \param G Graph that contains \p Node.
  /// \return True when \p Node should be hidden from the emitted graph.
  template <typename GraphType>
  static bool isNodeHidden(const void *Node, const GraphType &G) {
    return false;
  }

  /// Return true if nodes should be rendered with HTML-like labels.
  ///
  /// HTML-like labels allow colors and richer formatting in nodes and edge
  /// source labels.
  ///
  /// \return True when nodes and edge source labels use HTML-like formatting.
  static bool renderNodesUsingHTML() { return false; }

  /// Return the label to print inside the given node.
  ///
  /// \param Node Node whose label is requested.
  /// \param G Graph that contains \p Node.
  /// \return Label text drawn inside \p Node, or empty when none is set.
  template<typename GraphType>
  std::string getNodeLabel(const void *Node, const GraphType &G) {
    return "";
  }

  /// Return a unique identifier string for the given node.
  ///
  /// Typically an address or other unique token. Only used when non-empty.
  ///
  /// \param Node Node whose identifier label is requested.
  /// \param G Graph that contains \p Node.
  /// \return Unique identifier for \p Node, or empty when unused.
  template <typename GraphType>
  static std::string getNodeIdentifierLabel(const void *Node,
                                           const GraphType &G) {
    return "";
  }

  /// Return an optional longer description for the given node.
  ///
  /// \param Node Node whose description is requested.
  /// \param G Graph that contains \p Node.
  /// \return Longer description for \p Node, or empty when none is provided.
  template<typename GraphType>
  static std::string getNodeDescription(const void *Node, const GraphType &G) {
    return "";
  }

  /// Return custom DOT attributes for the given node.
  ///
  /// \param Node Node whose attributes are requested.
  /// \param G Graph that contains \p Node.
  /// \return DOT attribute string for \p Node, or empty when none are set.
  template<typename GraphType>
  static std::string getNodeAttributes(const void *Node,
                                       const GraphType &G) {
    return "";
  }

  /// Return custom DOT attributes for a particular edge.
  ///
  /// \param Node Source node of the edge.
  /// \param EI Iterator identifying the outgoing edge.
  /// \param G Graph that contains the edge.
  /// \return DOT attribute string for the edge, or empty when none are set.
  template<typename EdgeIter, typename GraphType>
  static std::string getEdgeAttributes(const void *Node, EdgeIter EI,
                                       const GraphType &G) {
    return "";
  }

  /// Return a label for the edge source itself, if any.
  ///
  /// \param Node Source node of the edge.
  /// \param EI Iterator identifying the outgoing edge.
  /// \return Label for the edge source, or empty when none is provided.
  template<typename EdgeIter>
  static std::string getEdgeSourceLabel(const void *Node, EdgeIter EI) {
    return "";
  }

  /// Return true if this outgoing edge should target another edge source.
  ///
  /// When true, the edge targets another edge source rather than a node. If
  /// this method is overridden, \c getEdgeTarget should be implemented too.
  ///
  /// \param Node Source node of the edge.
  /// \param EI Iterator identifying the outgoing edge.
  /// \return True when the edge targets another edge source instead of a node.
  template<typename EdgeIter>
  static bool edgeTargetsEdgeSource(const void *Node, EdgeIter EI) {
    return false;
  }

  /// Return the outgoing edge that is the target of this edge.
  ///
  /// Called when \c edgeTargetsEdgeSource returns true to determine which
  /// outgoing edge of \p Node is the target of this edge.
  ///
  /// \param Node Source node whose outgoing edges are considered.
  /// \param I Iterator identifying the outgoing edge used as the target.
  /// \return Iterator to the outgoing edge that this edge should target.
  template<typename EdgeIter>
  static EdgeIter getEdgeTarget(const void *Node, EdgeIter I) {
    return I;
  }

  /// hasEdgeDestLabels - If this function returns true, the graph is able
  /// to provide labels for edge destinations.
  ///
  /// \return True when edge destination labels are available for the graph.
  static bool hasEdgeDestLabels() {
    return false;
  }

  /// Return how many incoming edge destination labels the node has.
  ///
  /// Only meaningful when \c hasEdgeDestLabels returns true.
  ///
  /// \param Node Node whose incoming edge destination labels are counted.
  /// \return Number of incoming edge destination labels on \p Node.
  static unsigned numEdgeDestLabels(const void *Node) {
    return 0;
  }

  /// Return the incoming edge destination label at the given index.
  ///
  /// Only meaningful when \c hasEdgeDestLabels returns true.
  ///
  /// \param Node Node whose incoming edge destination labels are queried.
  /// \param Idx Zero-based index of the destination label to return.
  /// \return Destination label at \p Idx, or empty when none is provided.
  static std::string getEdgeDestLabel(const void *Node, unsigned Idx) {
    return "";
  }

  /// Emit graph features beyond ordinary nodes and edges.
  ///
  /// If a graph is made up of more than just straight-forward nodes and edges,
  /// this is the place to put all of the custom stuff necessary. The
  /// GraphWriter object, instantiated with your GraphType, is passed in as an
  /// argument. You may call arbitrary methods on it to add things to the output
  /// graph.
  ///
  /// \param G Graph being written.
  /// \param Writer Writer used to emit additional DOT features.
  template<typename GraphType, typename GraphWriter>
  static void addCustomGraphFeatures(const GraphType &G, GraphWriter &Writer) {}
};


/// Traits that customize how a graph type is converted to DOT.
///
/// Specialize for each graph type. When specializing, you may inherit from
/// DefaultDOTGraphTraits if you don't need to override everything.
template <typename Ty> struct DOTGraphTraits : DefaultDOTGraphTraits {
  /// Inherit constructors from DefaultDOTGraphTraits.
  using DefaultDOTGraphTraits::DefaultDOTGraphTraits;
};

} // End llvm namespace

#endif
